from collections import defaultdict


def adiciona(chave):
    palavras = input('Chave - {}: '.format(chave))
    if palavras:
        return [x.strip() for x in palavras.split(',')]
    else:
        return [chave]
 
d = {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['DEPOIS'],
             'GM': ['DEPOIS'],
             'PMC': ['DEPOIS'],
             'RH 13º salário': ['DEPOIS'],
             'SGM': ['DEPOIS'],
             'SIC': ['DEPOIS'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['DEPOIS'],
             'academia de ginástica': ['DEPOIS'],
             'agendamento': ['DEPOIS'],
             'agente de trânsito': ['DEPOIS'],
             'alvará de construção': ['DEPOIS'],
             'antipó': ['DEPOIS'],
             'arruamento': ['DEPOIS'],
             'atraso da linha': ['DEPOIS'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['DEPOIS'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['DEPOIS'],
             'cobrança de taxa sanepar': ['DEPOIS'],
             'coleta de caliça': ['DEPOIS'],
             'coleta de entulho': ['DEPOIS'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['DEPOIS'],
             'coleta de lixo vegetal': ['DEPOIS'],
             'coleta de poda de árvore': ['DEPOIS'],
             'coleta de terra': ['DEPOIS'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['DEPOIS'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['DEPOIS'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['DEPOIS'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['DEPOIS'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['DEPOIS'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['DEPOIS'],
             'estacionamento': ['DEPOIS'],
             'excesso de velocidade': ['DEPOIS'],
             'falta de medicamento': ['DEPOIS'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['DEPOIS'],
             'fiscalização de obras': ['DEPOIS'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['DEPOIS'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['DEPOIS'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['DEPOIS'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['DEPOIS'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['DEPOIS'],
             'iluminação': ['DEPOIS'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['DEPOIS'],
             'implantação de luminária': ['DEPOIS'],
             'imóvel da PMC': ['DEPOIS'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['DEPOIS'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['DEPOIS'],
             'integração': ['DEPOIS'],
             'iptu': ['DEPOIS'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['DEPOIS'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['DEPOIS'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['DEPOIS'],
             'lixo vegetal': ['DEPOIS'],
             'lâmpada': ['DEPOIS'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['DEPOIS'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['DEPOIS'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['DEPOIS'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['DEPOIS'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['DEPOIS'],
             'passeio': ['DEPOIS'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['DEPOIS'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['DEPOIS'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['DEPOIS'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['DEPOIS'],
             'propina': ['DEPOIS'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['DEPOIS'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['DEPOIS'],
             'refic': ['DEPOIS'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['DEPOIS'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['DEPOIS'],
             'saúde': ['DEPOIS'],
             'saúde ambiental': ['DEPOIS'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['DEPOIS'],
             'sgm': ['sgm'],
             'sigiloso': ['DEPOIS'],
             'sinalização vertical': ['DEPOIS'],
             'sme': ['sme'],
             'smf': ['DEPOIS'],
             'smma': ['smma'],
             'sms': ['DEPOIS'],
             'smu': ['smu'],
             'solicitação de restituição': ['DEPOIS'],
             'tapa buraco': ['DEPOIS'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['DEPOIS'],
             'trânsito em escolas': ['DEPOIS'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['DEPOIS'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['DEPOIS'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['DEPOIS'],
             'álvara de construção': ['DEPOIS']}

d = defaultdict(None,
            {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['DEPOIS'],
             'GM': ['DEPOIS'],
             'PMC': ['REMOVER'],
             'RH 13º salário': ['DEPOIS'],
             'SGM': ['sgm'],
             'SIC': ['DEPOIS'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['DEPOIS'],
             'academia de ginástica': ['DEPOIS'],
             'agendamento': ['DEPOIS'],
             'agente de trânsito': ['DEPOIS'],
             'alvará de construção': ['DEPOIS'],
             'antipó': ['DEPOIS'],
             'arruamento': ['REMOVER'],
             'atraso da linha': ['DEPOIS'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['DEPOIS'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['cmei'],
             'cobrança de taxa sanepar': ['DEPOIS'],
             'coleta de caliça': ['coleta de caliça'],
             'coleta de entulho': ['coleta de entulho'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['coleta de lixo'],
             'coleta de lixo vegetal': ['coleta de lixo vegetal'],
             'coleta de poda de árvore': ['DEPOIS'],
             'coleta de terra': ['coleta de caliça'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['DEPOIS'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['DEPOIS'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['remoção de toco'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['DEPOIS'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['DEPOIS'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['DEPOIS'],
             'estacionamento': ['DEPOIS'],
             'excesso de velocidade': ['DEPOIS'],
             'falta de medicamento': ['DEPOIS'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['DEPOIS'],
             'fiscalização de obras': ['DEPOIS'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['DEPOIS'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['fiscalização do comércio ambulante'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['DEPOIS'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['poluição sonora'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['hasteamento de bandeira'],
             'iluminação': ['DEPOIS'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['DEPOIS'],
             'implantação de luminária': ['DEPOIS'],
             'imóvel da PMC': ['DEPOIS'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['DEPOIS'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['dengue'],
             'integração': ['DEPOIS'],
             'iptu': ['iptu'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['DEPOIS'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['limpeza de caixa de captação'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['coleta de lixo'],
             'lixo vegetal': ['coleta de lixo vegetal'],
             'lâmpada': ['DEPOIS'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['DEPOIS'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['DEPOIS'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['DEPOIS'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['DEPOIS'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['REMOVER'],
             'passeio': ['DEPOIS'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['plantio de árvore'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['DEPOIS'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['DEPOIS'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['DEPOIS'],
             'propina': ['DEPOIS'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['DEPOIS'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['DEPOIS'],
             'refic': ['DEPOIS'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['DEPOIS'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['obra da sanepar'],
             'saúde': ['sms'],
             'saúde ambiental': ['DEPOIS'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['setran'],
             'sgm': ['sgm'],
             'sigiloso': ['DEPOIS'],
             'sinalização vertical': ['sinalização de trânsito'],
             'sme': ['sme'],
             'smf': ['smf'],
             'smma': ['smma'],
             'sms': ['sms'],
             'smu': ['smu'],
             'solicitação de restituição': ['REMOVER'],
             'tapa buraco': ['operação tapa buracos'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['DEPOIS'],
             'trânsito em escolas': ['DEPOIS'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['upa'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['urbs'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['DEPOIS'],
             'álvara de construção': ['DEPOIS']})
d = defaultdict(None,
            {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['obstrução de calçada'],
             'GM': ['guarda municipal'],
             'PMC': ['REMOVER'],
             'RH 13º salário': ['pagamento de salário'],
             'SGM': ['sgm'],
             'SIC': ['sic'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['abertura de rua'],
             'academia de ginástica': ['DEPOIS'],
             'agendamento': ['agendamento de visita médica'],
             'agente de trânsito': ['DEPOIS'],
             'alvará de construção': ['DEPOIS'],
             'antipó': ['DEPOIS'],
             'arruamento': ['REMOVER'],
             'atraso da linha': ['DEPOIS'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['DEPOIS'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['cmei'],
             'cobrança de taxa sanepar': ['cobrança de taxa de água'],
             'coleta de caliça': ['coleta de caliça'],
             'coleta de entulho': ['coleta de entulho'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['coleta de lixo'],
             'coleta de lixo vegetal': ['coleta de lixo vegetal'],
             'coleta de poda de árvore': ['DEPOIS'],
             'coleta de terra': ['coleta de caliça'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['REMOVER'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['corte de árvore'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['remoção de toco'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['DEPOIS'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['DEPOIS'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['DEPOIS'],
             'estacionamento': ['DEPOIS'],
             'excesso de velocidade': ['REMOVER'],
             'falta de medicamento': ['falta de medicamento'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['DEPOIS'],
             'fiscalização de obras': ['DEPOIS'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['fiscalização de saneamento'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['fiscalização do comércio ambulante'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['mosquito da dengue'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['poluição sonora'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['hasteamento de bandeira'],
             'iluminação': ['iluminação pública'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['implantação de lombada física'],
             'implantação de luminária': ['manutenção de luminária'],
             'imóvel da PMC': ['DEPOIS'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['inspeção de imóvel'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['dengue'],
             'integração': ['DEPOIS'],
             'iptu': ['iptu'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['DEPOIS'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['limpeza de caixa de captação'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['coleta de lixo'],
             'lixo vegetal': ['coleta de lixo vegetal'],
             'lâmpada': ['DEPOIS'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['DEPOIS'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['DEPOIS'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['DEPOIS'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['operação tapa buraco'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['REMOVER'],
             'passeio': ['DEPOIS'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['plantio de árvore'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['poda de árvore'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['poluição atmosférica'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['portal da transparência'],
             'propina': ['propina'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['DEPOIS'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['recuperação de calçada'],
             'refic': ['DEPOIS'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['DEPOIS'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['obra da sanepar'],
             'saúde': ['sms'],
             'saúde ambiental': ['DEPOIS'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['setran'],
             'sgm': ['sgm'],
             'sigiloso': ['DEPOIS'],
             'sinalização vertical': ['sinalização de trânsito'],
             'sme': ['sme'],
             'smf': ['smf'],
             'smma': ['smma'],
             'sms': ['sms'],
             'smu': ['smu'],
             'solicitação de restituição': ['REMOVER'],
             'tapa buraco': ['operação tapa buracos'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['troca de lâmpada'],
             'trânsito em escolas': ['DEPOIS'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['upa'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['urbs'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['DEPOIS'],
             'álvara de construção': ['álvara de construção']})
d = defaultdict(None,
            {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['obstrução de calçada'],
             'GM': ['guarda municipal'],
             'PMC': ['REMOVER'],
             'RH 13º salário': ['pagamento de salário'],
             'SGM': ['sgm'],
             'SIC': ['sic'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['abertura de rua'],
             'academia de ginástica': ['DEPOIS'],
             'agendamento': ['agendamento de visita médica'],
             'agente de trânsito': ['DEPOIS'],
             'alvará de construção': ['DEPOIS'],
             'antipó': ['DEPOIS'],
             'arruamento': ['REMOVER'],
             'atraso da linha': ['atraso de transporte público'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['REMOVER'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['cmei'],
             'cobrança de taxa sanepar': ['cobrança de taxa de água'],
             'coleta de caliça': ['coleta de caliça'],
             'coleta de entulho': ['coleta de entulho'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['coleta de lixo'],
             'coleta de lixo vegetal': ['coleta de lixo vegetal'],
             'coleta de poda de árvore': ['DEPOIS'],
             'coleta de terra': ['coleta de caliça'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['REMOVER'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['corte de árvore'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['remoção de toco'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['DEPOIS'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['DEPOIS'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['smelj'],
             'estacionamento': ['fechamento de estacionamento'],
             'excesso de velocidade': ['REMOVER'],
             'falta de medicamento': ['falta de medicamento'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['fiscalização de comércio'],
             'fiscalização de obras': ['fiscalização de obras'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['fiscalização de saneamento'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['fiscalização do comércio ambulante'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['mosquito da dengue'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['poluição sonora'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['hasteamento de bandeira'],
             'iluminação': ['iluminação pública'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['implantação de lombada física'],
             'implantação de luminária': ['manutenção de luminária'],
             'imóvel da PMC': ['DEPOIS'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['inspeção de imóvel'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['dengue'],
             'integração': ['DEPOIS'],
             'iptu': ['iptu'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['DEPOIS'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['limpeza de caixa de captação'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['coleta de lixo'],
             'lixo vegetal': ['coleta de lixo vegetal'],
             'lâmpada': ['troca de lâmpada'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['DEPOIS'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['DEPOIS'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['DEPOIS'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['operação tapa buraco'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['REMOVER'],
             'passeio': ['DEPOIS'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['plantio de árvore'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['poda de árvore'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['poluição atmosférica'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['portal da transparência'],
             'propina': ['propina'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['DEPOIS'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['recuperação de calçada'],
             'refic': ['refic'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['relatório de vistoria'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['obra da sanepar'],
             'saúde': ['sms'],
             'saúde ambiental': ['REMOVER'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['setran'],
             'sgm': ['sgm'],
             'sigiloso': ['DEPOIS'],
             'sinalização vertical': ['sinalização de trânsito'],
             'sme': ['sme'],
             'smf': ['smf'],
             'smma': ['smma'],
             'sms': ['sms'],
             'smu': ['smu'],
             'solicitação de restituição': ['REMOVER'],
             'tapa buraco': ['operação tapa buracos'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['troca de lâmpada'],
             'trânsito em escolas': ['REMOVER'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['upa'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['urbs'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['REMOVER'],
             'álvara de construção': ['álvara de construção']})

d = defaultdict(None,
            {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['obstrução de calçada'],
             'GM': ['guarda municipal'],
             'PMC': ['REMOVER'],
             'RH 13º salário': ['pagamento de salário'],
             'SGM': ['sgm'],
             'SIC': ['sic'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['abertura de rua'],
             'academia de ginástica': ['DEPOIS'],
             'agendamento': ['agendamento de visita médica'],
             'agente de trânsito': ['DEPOIS'],
             'alvará de construção': ['DEPOIS'],
             'antipó': ['DEPOIS'],
             'arruamento': ['REMOVER'],
             'atraso da linha': ['atraso de transporte público'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['REMOVER'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['cmei'],
             'cobrança de taxa sanepar': ['cobrança de taxa de água'],
             'coleta de caliça': ['coleta de caliça'],
             'coleta de entulho': ['coleta de entulho'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['coleta de lixo'],
             'coleta de lixo vegetal': ['coleta de lixo vegetal'],
             'coleta de poda de árvore': ['DEPOIS'],
             'coleta de terra': ['coleta de caliça'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['REMOVER'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['corte de árvore'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['remoção de toco'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['DEPOIS'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['DEPOIS'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['smelj'],
             'estacionamento': ['fechamento de estacionamento'],
             'excesso de velocidade': ['REMOVER'],
             'falta de medicamento': ['falta de medicamento'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['fiscalização de comércio'],
             'fiscalização de obras': ['fiscalização de obras'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['fiscalização de saneamento'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['fiscalização do comércio ambulante'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['mosquito da dengue'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['poluição sonora'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['hasteamento de bandeira'],
             'iluminação': ['iluminação pública'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['implantação de lombada física'],
             'implantação de luminária': ['manutenção de luminária'],
             'imóvel da PMC': ['DEPOIS'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['inspeção de imóvel'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['dengue'],
             'integração': ['DEPOIS'],
             'iptu': ['iptu'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['DEPOIS'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['limpeza de caixa de captação'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['coleta de lixo'],
             'lixo vegetal': ['coleta de lixo vegetal'],
             'lâmpada': ['troca de lâmpada'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['DEPOIS'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['DEPOIS'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['DEPOIS'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['operação tapa buraco'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['REMOVER'],
             'passeio': ['DEPOIS'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['plantio de árvore'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['poda de árvore'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['poluição atmosférica'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['portal da transparência'],
             'propina': ['propina'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['DEPOIS'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['recuperação de calçada'],
             'refic': ['refic'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['relatório de vistoria'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['obra da sanepar'],
             'saúde': ['sms'],
             'saúde ambiental': ['REMOVER'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['setran'],
             'sgm': ['sgm'],
             'sigiloso': ['DEPOIS'],
             'sinalização vertical': ['sinalização de trânsito'],
             'sme': ['sme'],
             'smf': ['smf'],
             'smma': ['smma'],
             'sms': ['sms'],
             'smu': ['smu'],
             'solicitação de restituição': ['REMOVER'],
             'tapa buraco': ['operação tapa buracos'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['troca de lâmpada'],
             'trânsito em escolas': ['REMOVER'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['upa'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['urbs'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['REMOVER'],
             'álvara de construção': ['álvara de construção']}) 

d = defaultdict(None,
            {'CMC': ['CMC'],
             'CORTE ARVORE, MANUTENÇÃO PRAÇA': ['DEPOIS'],
             'Calçada em más condições': ['obstrução de calçada'],
             'GM': ['guarda municipal'],
             'PMC': ['REMOVER'],
             'RH 13º salário': ['pagamento de salário'],
             'SGM': ['sgm'],
             'SIC': ['sic'],
             'UCE30 - INTERLOCUTÓRIO PLANTÃO TÉCNICO': ['DEPOIS'],
             'abertura de rua': ['abertura de rua'],
             'academia de ginástica': ['REMOVER'],
             'agendamento': ['agendamento de visita médica'],
             'agente de trânsito': ['agente de trânsito'],
             'alvará de construção': ['alvará de construção'],
             'antipó': ['DEPOIS'],
             'arruamento': ['REMOVER'],
             'atraso da linha': ['atraso de transporte público'],
             'auditoria central 156': ['DEPOIS'],
             'avaliação técnica': ['REMOVER'],
             'avaliação técnica corte da árvore': ['DEPOIS'],
             'bloqueio de testada': ['bloqueio de testada'],
             'boleto': ['DEPOIS'],
             'caixa de captação': ['limpeza de caixa de captação'],
             'campanha doe calor': ['DEPOIS'],
             'caps': ['DEPOIS'],
             'cartão do armazem da familia': ['DEPOIS'],
             'cartão transporte': ['DEPOIS'],
             'caçambas': ['DEPOIS'],
             'central de leito': ['central de leito'],
             'cmei': ['cmei'],
             'cobrança de taxa sanepar': ['cobrança de taxa de água'],
             'coleta de caliça': ['coleta de caliça'],
             'coleta de entulho': ['coleta de entulho'],
             'coleta de entulho e terra': ['DEPOIS'],
             'coleta de galhos': ['DEPOIS'],
             'coleta de lixo': ['coleta de lixo'],
             'coleta de lixo vegetal': ['coleta de lixo vegetal'],
             'coleta de poda de árvore': ['coleta de lixo vegetal'],
             'coleta de terra': ['coleta de caliça'],
             'coleta lixo vegetal': ['coleta lixo vegetal'],
             'coleta resíduos vegetais': ['DEPOIS'],
             'concurso': ['REMOVER'],
             'conselho tutelar': ['DEPOIS'],
             'corte de árvore': ['corte de árvore'],
             'cosedi': ['DEPOIS'],
             'dengue': ['DEPOIS'],
             'denúncia': ['DEPOIS'],
             'destoca de árvore': ['remoção de toco'],
             'diversos protocolos': ['fiscalização de trânsito'],
             'drenagem': ['REMOVER'],
             'drenagem erosão em galerias pluvias': ['DEPOIS'],
             'drenagem rio': ['drenagem de rio'],
             'educação': ['sme'],
             'elogio': ['REMOVER'],
             'erosão em galeria de águas pluviais': ['DEPOIS'],
             'erosão em margem de rio/córrego': ['DEPOIS'],
             'esporte e lazer': ['smelj'],
             'estacionamento': ['fechamento de estacionamento'],
             'excesso de velocidade': ['REMOVER'],
             'falta de medicamento': ['falta de medicamento'],
             'finanças': ['DEPOIS'],
             'fiscalização': ['DEPOIS'],
             'fiscalização de comércio': ['fiscalização de comércio'],
             'fiscalização de estabelecimento comercial': ['fiscalização de comércio'],
             'fiscalização de obras': ['fiscalização de obras'],
             'fiscalização de publicidade': ['DEPOIS'],
             'fiscalização de saneamento': ['fiscalização de saneamento'],
             'fiscalização de terreno': ['fiscalização de terreno'],
             'fiscalização de trânsito': ['fiscalização de trânsito'],
             'fiscalização do comércio ambulante': ['fiscalização do comércio ambulante'],
             'fiscalização industrial': ['DEPOIS'],
             'focos de mosquito': ['mosquito da dengue'],
             'funcionamento da escola municipal': ['DEPOIS'],
             'funcionamento do parque': ['poluição sonora'],
             'guia rebaixada': ['DEPOIS'],
             'hasteamento da bandeira': ['hasteamento de bandeira'],
             'iluminação': ['iluminação pública'],
             'iluminação pública': ['iluminação pública'],
             'iluminação pública lâmpada queimada': ['iluminação pública',
              'troca de lâmapada'],
             'implantação antipó': ['DEPOIS'],
             'implantação asfalto': ['DEPOIS'],
             'implantação de lombada física': ['implantação de lombada física'],
             'implantação de luminária': ['manutenção de luminária'],
             'imóvel da PMC': ['imóvel alugado pela pmc'],
             'infrações de trânsito': ['DEPOIS'],
             'inspeção': ['inspeção de imóvel'],
             'inspeção do mosquito da dengue': ['DEPOIS'],
             'inspeção/orientação do mosquito da dengue': ['dengue'],
             'integração': ['DEPOIS'],
             'iptu': ['iptu'],
             'itbi': ['DEPOIS'],
             'lançamento de esgoto': ['REMOVER'],
             'lei': ['legislação municipal'],
             'limpeza de caixa de captação': ['DEPOIS'],
             'limpeza de terreno': ['DEPOIS'],
             'limpeza de valeta': ['DEPOIS'],
             'limpeza e desobstrução da caixa de captação': ['limpeza de caixa de captação'],
             'limpeza e desobstrução de caixa de captação': ['limpeza de caixa de captação'],
             'lixo domiciliar': ['coleta de lixo'],
             'lixo vegetal': ['coleta de lixo vegetal'],
             'lâmpada': ['troca de lâmpada'],
             'lâmpada oscilando': ['DEPOIS'],
             'lâmpada queimada': ['troca de lâmpada'],
             'macrodrenagem': ['DEPOIS'],
             'manutenção da luminária': ['manutenção de luminária'],
             'manutenção da praça': ['manutenção da praça'],
             'manutenção de luminária': ['manutenção de luminária'],
             'material asfáltico': ['coleta de material asfáltico'],
             'meio ambiente': ['DEPOIS'],
             'multa': ['notificação de multa'],
             'notificação': ['notificação de multa'],
             'novo portal (Central 156)': ['DEPOIS'],
             'obras': ['smop'],
             'obras/sgm': ['smop', 'sgm'],
             'operação tapa buraco': ['operação tapa buraco'],
             'ouvidoria': ['ouvidoria'],
             'pagamento em duplicidade': ['restituição de pagamento em duplicidade'],
             'parcelamento do solo': ['REMOVER'],
             'passeio': ['REMOVER'],
             'pavimentação': ['DEPOIS'],
             'pavimentação alternativa': ['DEPOIS'],
             'pavimentação definitiva': ['REMOVER'],
             'pavimentação tapa buraco': ['DEPOIS'],
             'placa caída': ['sinalização de trânsito'],
             'plantio de árvore': ['plantio de árvore'],
             'poda de arvore': ['DEPOIS'],
             'poda de árvore': ['poda de árvore'],
             'pode de árvore': ['poda de árvore'],
             'poluição atmosférica': ['poluição atmosférica'],
             'poluição sonora': ['DEPOIS'],
             'portal da transparência': ['portal da transparência'],
             'propina': ['propina'],
             'radar cidadão': ['radar cidadão'],
             'reciclagem de ruas em antipó': ['DEPOIS'],
             'reciclavel': ['REMOVER'],
             'reclamação upa': ['REMOVER'],
             'reclamações de atendimento': ['DEPOIS'],
             'recuperação de calçada': ['recuperação de calçada'],
             'refic': ['refic'],
             'reforma calçada': ['DEPOIS'],
             'relatório de vistoria': ['relatório de vistoria'],
             'resposta do serviço 156': ['central 156'],
             'restos de construção': ['DEPOIS'],
             'revitalização': ['REMOVER'],
             'revitalização de antipó': ['DEPOIS'],
             'roçada em terreno': ['DEPOIS'],
             'roçada em terrenos públicos': ['DEPOIS'],
             'sanepar': ['obra da sanepar'],
             'saúde': ['sms'],
             'saúde ambiental': ['REMOVER'],
             'seguro desemprego': ['DEPOIS'],
             'setor de análise': ['DEPOIS'],
             'setran': ['setran'],
             'sgm': ['sgm'],
             'sigiloso': ['sigiloso'],
             'sinalização vertical': ['sinalização de trânsito'],
             'sme': ['sme'],
             'smf': ['smf'],
             'smma': ['smma'],
             'sms': ['sms'],
             'smu': ['smu'],
             'solicitação de restituição': ['REMOVER'],
             'tapa buraco': ['operação tapa buracos'],
             'taxi': ['DEPOIS'],
             'transporte coletivo': ['DEPOIS'],
             'tração animal': ['DEPOIS'],
             'troca de lâmpada': ['troca de lâmpada'],
             'trânsito em escolas': ['REMOVER'],
             'unidade básica de saúde': ['unidade básica de saúde'],
             'unidade de saúde': ['DEPOIS'],
             'upa': ['upa'],
             'urbanismo': ['DEPOIS'],
             'urbs': ['urbs'],
             'veículo estacionado na calçada': ['DEPOIS'],
             'álvara': ['REMOVER'],
             'álvara de construção': ['álvara de construção']})
 
