from rake import remove_unwanted_patterns
import pytest


desc1 = ('Iluminação pública'
         'Cidadã reclama da demora para substituição de lâmpadas de iluminação '
         'pública. Protocolo na Central 156 nº6359266, registrado em 14/03/2016 16:07. '
         'Identificação das luminárias  BSR-ANR E BSS-AR1.')
out1 = ('Iluminação pública'
        'Cidadã reclama da demora para substituição de lâmpadas de iluminação '
        'pública. Protocolo na Central 156 nº, registrado em  . '
         'Identificação das luminárias   E .')

desc2 = ('Iluminação Publica'
         'Foram abertos vários protocolos para substituição de lâmpadas queimadas na '
         'rua Dr. Alceu Amaral Ferreira - Bom Retiro - 80.520-520. Sequencia de 3 '
         'postes sem iluminação o que compromete e muito,  a segurança publica.\r\n'
         'Protocolo 6497353 (em frente à residencia 325)\r\n'
         'Protocolo 6526565  da luminária BMA-AJV (em frente à residencia 325);  '
         '6526566  da luminária BMA-A15 (em frente à residencia 301) e 6526567  da '
         'luminária BMA-AH4 (em frente à residencia 269)')
out2 = ('Iluminação Publica'
        'Foram abertos vários protocolos para substituição de lâmpadas queimadas na '
        'rua Dr. Alceu Amaral Ferreira - Bom Retiro - . Sequencia de 3 '
        'postes sem iluminação o que compromete e muito,  a segurança publica.\r\n'
        'Protocolo  (em frente à residencia 325)\r\n'
        'Protocolo   da luminária  (em frente à residencia 325);  '
        '  da luminária  (em frente à residencia 301) e   da '
        'luminária  (em frente à residencia 269)')

desc3 = ('Andamento de protocolo'
         'Na data 16/02/2015 registrei o protocolo 5775098. Ate hoje 30/04/2015 não '
         'obtive resposta. Liguei no 156 nas datas 09/03/2015, e 08/04/2015, sempre '
         'bem atendido, e nem com essa ajuda de registrar meu reclamo mais uma vez, '
         'obtive resposta. Não poder verificar meu pedido por falta de funcionários e '
         'ate compreensivel, agora ignorar o mesmo e desrespeito. Obrigado.')
out3 = ('Andamento de protocolo'
        'Na data  registrei o protocolo . Ate hoje  não '
         'obtive resposta. Liguei no 156 nas datas , e , sempre '
         'bem atendido, e nem com essa ajuda de registrar meu reclamo mais uma vez, '
         'obtive resposta. Não poder verificar meu pedido por falta de funcionários e '
         'ate compreensivel, agora ignorar o mesmo e desrespeito. Obrigado.')

desc4 = ('Poste sem luz há mais de 4 meses'
         'Eu e meus irmãos já fizemos diversos protocolos por telefone e internet a '
         'respeito do poste da frente da minha casa e continuo sem luz (código do '
         'poste BXF-ALY). O primeiro (6404887 de 12/04) continua em aberto, depois '
         'fizemos outros: 389513i, 392767i, 395043i, 6530539, 6499069, 6533816, '
         '6532180. O problema nunca foi a lâmpada, ela funcionava de forma '
         'intermitente, acendia e apagava a noite toda, mas ficava mais apagada do que '
         'acesa. Veio uma equipe dias após a primeira solicitação, pararam o caminhão '
         'debaixo do poste num momento em que a lâmpada estava acesa, ficaram menos de '
         '5 minutos e foram embora. Outra equipe veio no dia 01/07 e trocou a lâmpada. '
         'No dia seguinte começou a dar curto circuito na lâmpada, o que refletiu no '
         'funcionamento dos aparelhos de dentro da minha casa: a energia da geladeira, '
         'micro-ondas, freezer e estabilizador começou a "pipocar". Avisei o 156 '
         'pedindo urgência e nada.\r\n'
         'Liguei para a emergência da Copel (protocolo 01178695640 de 14/07) e em '
         'menos de 1 hora veio uma equipe e cortaram a conexão do poste por conta das '
         'faíscas. Estamos sem luz! Já entrei em contato com o 156 e todos dizem que '
         'colocaram urgência na solicitação. Ontem solicitei pelo chat e o menino '
         'também colocou urgência, todos no protocolo 6532180.\r\n'
         'No site da prefeitura está escrito que solicitações de urgência e emergência '
         'devem ser registradas pelo 156 ou chat, mas não diz que a urgência da '
         'Secretaria de Obras demora o tempo que eles querem. Estamos sem luz e com '
         'muito medo! Por favor, solucionem o problema!')
out4 = ('Poste sem luz há mais de 4 meses'
        'Eu e meus irmãos já fizemos diversos protocolos por telefone e internet a '
        'respeito do poste da frente da minha casa e continuo sem luz (código do '
        'poste ). O primeiro ( de ) continua em aberto, depois '
        'fizemos outros: , , , , , , '
        '. O problema nunca foi a lâmpada, ela funcionava de forma '
         'intermitente, acendia e apagava a noite toda, mas ficava mais apagada do que '
         'acesa. Veio uma equipe dias após a primeira solicitação, pararam o caminhão '
         'debaixo do poste num momento em que a lâmpada estava acesa, ficaram menos de '
         '5 minutos e foram embora. Outra equipe veio no dia  e trocou a lâmpada. '
         'No dia seguinte começou a dar curto circuito na lâmpada, o que refletiu no '
         'funcionamento dos aparelhos de dentro da minha casa: a energia da geladeira, '
         'micro-ondas, freezer e estabilizador começou a "pipocar". Avisei o 156 '
         'pedindo urgência e nada.\r\n'
         'Liguei para a emergência da Copel (protocolo  de ) e em '
         'menos de 1 hora veio uma equipe e cortaram a conexão do poste por conta das '
         'faíscas. Estamos sem luz! Já entrei em contato com o 156 e todos dizem que '
         'colocaram urgência na solicitação. Ontem solicitei pelo chat e o menino '
         'também colocou urgência, todos no protocolo .\r\n'
         'No site da prefeitura está escrito que solicitações de urgência e emergência '
         'devem ser registradas pelo 156 ou chat, mas não diz que a urgência da '
         'Secretaria de Obras demora o tempo que eles querem. Estamos sem luz e com '
         'muito medo! Por favor, solucionem o problema!')

desc5 = ('Iluminação pública'
         'Cidadão solicita manutenção de luminária: A41-AC5, protocolo central 156: ' 
         '6532246')
out5 = ('Iluminação pública'
         'Cidadão solicita manutenção de luminária: , protocolo central 156: ' 
         '')

desc6 = ('Iluminação pública'
         'Cidadão solicita manutenção de luminária F7D-AQV., protocolo central 156: '
         '6461915 Consta como atendido mas até o momento nada foi feito.')
out6 = ('Iluminação pública'
         'Cidadão solicita manutenção de luminária ., protocolo central 156: '
         ' Consta como atendido mas até o momento nada foi feito.')

desc7 = ('Fiscalização de trânsito'
         'Cidadã solicita fiscalização de trânsito em virtude de um caminhão da '
         'prefeitura placa AWH-6092, que está estacionado em guia rebaixada impedindo '
         'o acesso à residência. Protocolo central 156: ')
out7 = ('Fiscalização de trânsito'
        'Cidadã solicita fiscalização de trânsito em virtude de um caminhão da '
        'prefeitura placa , que está estacionado em guia rebaixada impedindo '
        'o acesso à residência. Protocolo central 156: ')

desc8 = ('Pista de skate'
         '\r\n'
         '\r\n'
         'Desde final de 2013, com denúncia de pista de skate ilegal do bar John Bull '
         'não recebemos resposta alguma. Foi entrado com abaixo-assinado de moradores '
         'do parque João Paulo no urbanismo contra essa pista absurda e tb não '
         'recebemos respostas alguma, inclusive fiscais atendendo mal, desligando '
         'telefone na cara, protegendo descaradamente o dono do bar, engavetando o '
         'processo. Protocolo do urbanismo 01-076548/2014. Essa pista fica entorno de '
         'bem tombado, estava embargada e de repente tudo mudou e deram alvara pra '
         'esse absurdo sem nos dizer nada. Esse bar faz o q. quer e bem entende aqui '
         'atrás de residências do parque, constrói o q. quer, incomoda todos com '
         'barulho insano e jamais é punido, aliás é agraciado com álvaras ilegais, só '
         'podemos desconfiar de algo como corrupção!\r\n')
out8 = ('Pista de skate'
         '\r\n'
         '\r\n'
         'Desde final de , com denúncia de pista de skate ilegal do bar John Bull '
         'não recebemos resposta alguma. Foi entrado com abaixo-assinado de moradores '
         'do parque João Paulo no urbanismo contra essa pista absurda e tb não '
         'recebemos respostas alguma, inclusive fiscais atendendo mal, desligando '
         'telefone na cara, protegendo descaradamente o dono do bar, engavetando o '
         'processo. Protocolo do urbanismo . Essa pista fica entorno de '
         'bem tombado, estava embargada e de repente tudo mudou e deram alvara pra '
         'esse absurdo sem nos dizer nada. Esse bar faz o q. quer e bem entende aqui '
         'atrás de residências do parque, constrói o q. quer, incomoda todos com '
         'barulho insano e jamais é punido, aliás é agraciado com álvaras ilegais, só '
         'podemos desconfiar de algo como corrupção!\r\n')

desc9 = ('linhas de onibus agua verde-juvevê e agua-verde abranches que passarão a '
         'operar somente por cartão transporte'
         'Esta semana fui surpreendida por um aviso nos ônibus que fazem a linha agua '
         'verde- juvevê e agua verde - abranches informando que a partir do dia '
         '04/06/2015 elas somente operarão com cartão transporte, não mais com a '
         'presença do cobrador.\r\n'
         '\r\n'
         'Gostaria de solicitar que não fosse permitida esta alteração, pois ela irá '
         'prejudicar muitos moradores das respectivas linhas que, por não utilizarem o '
         'transporte continuamente, não possuem cartão e fazem o pagamento com '
         'dinheiro. A linha perderá passageiros, pois agora seremos obrigados a nos '
         'dirigir aos ônibus biarticulados da rua República Argentina, únicos que '
         'aceitarão o pagamento com dinheiro. Deve-se proporcionar ao cidadão mais '
         'opções de pagamento e acesso e não diminuí-las como estão fazendo.\r\n'
         '\r\n'
         'Além disso, a presença do cobrador nestas linhas de ônibus é essencial, pois '
         'o bairro água verde possui uma grande população de idosos, que utilizam '
         'estas linhas diariamente e precisam da ajuda do cobrador para subir e descer '
         'dos ônibus, muitos inclusive em cadeiras de rodas. Esta função não pode ser '
         'desempenhada pelo motorista, pelo que a alteração ainda prejudicará ainda '
         'mais a população mais necessitada de ajuda.\r\n'
         '\r\n')
out9 = ('linhas de onibus agua verde-juvevê e agua-verde abranches que passarão a '
         'operar somente por cartão transporte'
         'Esta semana fui surpreendida por um aviso nos ônibus que fazem a linha agua '
         'verde- juvevê e agua verde - abranches informando que a partir do dia '
         ' elas somente operarão com cartão transporte, não mais com a '
         'presença do cobrador.\r\n'
         '\r\n'
         'Gostaria de solicitar que não fosse permitida esta alteração, pois ela irá '
         'prejudicar muitos moradores das respectivas linhas que, por não utilizarem o '
         'transporte continuamente, não possuem cartão e fazem o pagamento com '
         'dinheiro. A linha perderá passageiros, pois agora seremos obrigados a nos '
         'dirigir aos ônibus biarticulados da rua República Argentina, únicos que '
         'aceitarão o pagamento com dinheiro. Deve-se proporcionar ao cidadão mais '
         'opções de pagamento e acesso e não diminuí-las como estão fazendo.\r\n'
         '\r\n'
         'Além disso, a presença do cobrador nestas linhas de ônibus é essencial, pois '
         'o bairro água verde possui uma grande população de idosos, que utilizam '
         'estas linhas diariamente e precisam da ajuda do cobrador para subir e descer '
         'dos ônibus, muitos inclusive em cadeiras de rodas. Esta função não pode ser '
         'desempenhada pelo motorista, pelo que a alteração ainda prejudicará ainda '
         'mais a população mais necessitada de ajuda.\r\n'
         '\r\n')

desc10 = ('156 '
          'Reclamação quanto ao protocolo de número 5549081, do mês de setembro de '
          '2014, até agora sem resposta. Tapa buraco na rua Carlos Estrela Moreira - '
          'Pilarzinho')
out10 = ('156 '
          'Reclamação quanto ao protocolo de número , do mês de setembro de '
          ', até agora sem resposta. Tapa buraco na rua Carlos Estrela Moreira - '
          'Pilarzinho')

desc11 = ('anti-pó'
          'Reclamação pelo não atendimento do pedido de anti-pó para a Rua Doutor '
          'Hamilton Dybowicz, 200. CEP 81570-080, feito por meio da Central 156, último '
          'protocolo nr. 598624.')
out11 = ('anti-pó'
         'Reclamação pelo não atendimento do pedido de anti-pó para a Rua Doutor '
         'Hamilton Dybowicz, 200. CEP , feito por meio da Central 156, último '
         'protocolo nr. .')

desc12 = ('descumprimento da lei 12.527/11 ( lei de acesso a informação)'
          'Tenho desde novembro de 2014 protocolo de requerimento  de nº '
          '74-0001.152/2014 de acesso a informação (lei 12.527/11 e decreto 1.135)e até '
          'o momento não se obtem cópia dos documentos solicitados.É a 2ª vez que '
          'solicito providências a esta ouvidoria referente a este requerimento de '
          'acesso a informação de nº 74-0001.152/2014.\r\n'
          '\r\n'
          'Solicito providências ao senhor ouvidor de Curitiba.')
out12 = ('descumprimento da lei  ( lei de acesso a informação)'
         'Tenho desde novembro de  protocolo de requerimento  de nº '
         ' de acesso a informação (lei  e decreto )e até '
         'o momento não se obtem cópia dos documentos solicitados.É a 2ª vez que '
         'solicito providências a esta ouvidoria referente a este requerimento de '
         'acesso a informação de nº .\r\n'
         '\r\n'
         'Solicito providências ao senhor ouvidor de Curitiba.')

desc13 = ('Som alto'
          'Protocolo: \r\n'
          '\t  6013023\r\n'
          'Situação: \r\n'
          '\t  RESPONDIDO PELO RESPONSÁVEL\r\n'
          '\r\n'
          'Data de Criação: \r\n'
          '\t  28/07/2015 09:09\r\n'
          'Descrição: \r\n'
          '\t  SOLICITA FISCALIZAÇÃO QUANTO A POLUIÇÃO SONORA NOTURNA, OCASIONADA POR '
          'UM BAR NO ENDEREÇO CITADO, AFIRMA QUE NOS FINAIS DE SEMANA HÁ ENCONTROS DE '
          'MOTO NO BAR E MÚSICA ALTA O TEMPO TODO. PORÉM O QUE INCOMODA MAIS É A NOITE. '
          'JÁ REGISTROU ALVARÁ DE FISCALIZAÇÃO DE ALVARÁ: 5780572. E SOLICITA URGÊNCIA, '
          'POIS O SOM É MUITO ALTO E INCOMODA MUITO, JÁ ENTROU EM CONTATO COM A POLÍCIA '
          'TAMBÉM, HÁ BANDA TOCANDO AO VIVO NO LOCAL. E MUITAS MOTOS CIRCULANDO NO '
          'LOCAL COM BARULHO ALTO DOS MOTORES.\r\n'
          'Assunto: \r\n'
          '\t  POLUIÇÃO\r\n'
          'Subdivisão: \r\n'
          '\t  SONORA - NOTURNA\r\n'
          '\r\n'
          '\r\n'
          'Usuário SIMA: SOLICITACAO ENCAMINHADA A DIVISAO DE FISCALIZACAO A SECRETARIA '
          'MUNICIPAL DO MEIO AMBIENTE ONDE SERA INICIADA ACAO FISCAL ATRAVES DO '
          'PROTOCOLO FIS-154699,INFORMACOES DA ACAO FISCAL PODERAO SER OBTIDAS PELO '
          'FONE 3350-9240/SMMA/ DIVISAO DE FISCALIZAÇÃO. ')
out13 = ('Som alto'
         'Protocolo: \r\n'
         '\t  \r\n'
         'Situação: \r\n'
         '\t  RESPONDIDO PELO RESPONSÁVEL\r\n'
         '\r\n'
         'Data de Criação: \r\n'
         '\t   \r\n'
         'Descrição: \r\n'
         '\t  SOLICITA FISCALIZAÇÃO QUANTO A POLUIÇÃO SONORA NOTURNA, OCASIONADA POR '
         'UM BAR NO ENDEREÇO CITADO, AFIRMA QUE NOS FINAIS DE SEMANA HÁ ENCONTROS DE '
         'MOTO NO BAR E MÚSICA ALTA O TEMPO TODO. PORÉM O QUE INCOMODA MAIS É A NOITE. '
         'JÁ REGISTROU ALVARÁ DE FISCALIZAÇÃO DE ALVARÁ: . E SOLICITA URGÊNCIA, '
         'POIS O SOM É MUITO ALTO E INCOMODA MUITO, JÁ ENTROU EM CONTATO COM A POLÍCIA '
         'TAMBÉM, HÁ BANDA TOCANDO AO VIVO NO LOCAL. E MUITAS MOTOS CIRCULANDO NO '
         'LOCAL COM BARULHO ALTO DOS MOTORES.\r\n'
         'Assunto: \r\n'
         '\t  POLUIÇÃO\r\n'
         'Subdivisão: \r\n'
         '\t  SONORA - NOTURNA\r\n'
         '\r\n'
         '\r\n'
         'Usuário SIMA: SOLICITACAO ENCAMINHADA A DIVISAO DE FISCALIZACAO A SECRETARIA '
         'MUNICIPAL DO MEIO AMBIENTE ONDE SERA INICIADA ACAO FISCAL ATRAVES DO '
         'PROTOCOLO ,INFORMACOES DA ACAO FISCAL PODERAO SER OBTIDAS PELO '
         'FONE /SMMA/ DIVISAO DE FISCALIZAÇÃO. ')

desc14 = ('Retirada de árvores As árvores estão destruindo a calçada.\r\n'
          '\r\nProtocolo: \r\n\t  6042604\r\nSituação: \r\n\t  ABERTA\r\n'
          'Email: \r\n\t  \r\nData de Criação: \r\n\t  17/08/2015 09:59\r\n'
          '\r\n Dados do Assunto\r\nDescrição: \r\n\t  SOLICITA A RETIRADA '
          'DE DOIS ALFENEIROS DA VIA MENCIONADA. RELATA QUE ELES ESTÃO '
          'AFETANDO A TUBULAÇÃO DE GÁ E A CALÇADA ESTÁ TODA DANIFICADA. '
          'CIDADÃO RELATA QUE REFERENTE A ESTA SITUAÇÃO, JÁ FOI DADA '
          'ENTRADA NA RUA DA CIDADANIA DO PINHEIRINHO, UMA DAS DATAS DE '
          'ENTRADA É 17-06-2015 COM O PARECER TÉCNICO: ARP15001010 E ELES '
          'ENCAMINHARAM PARA O HORTO MUNCIPAL. RELATA QUE ESTÁ UM JOGO DE '
          'EMPURRA EMPURRA, E NINGÚEM RESOLVE O PROBLEMA. PEDE VERIFICAÇÃO '
          'COM URGÊNCIA.\r\nAssunto: \r\n\t  ÁRVORE\r\nSubdivisão: \r\n'
          '\t  AVALIAÇÃO TÉCNICA - VIA PÚBLICA\r\nEndereço: \r\n\t\r\n'
          'Bairro: \r\n\t  AGUA VERDE\r\nRegional: \r\n\t  Unidade '
          'Regional Portao\r\nCep: \r\n\t  \r\nTransversal 1: \r\n'
          '\t  R. SANTA CATARINA\r\nTransversal 2: \r\n\t  R. RIO GRANDE '
          'DO SUL\r\nCidade: \r\n\t  CURITIBA -  PR\r\nPonto de Ref.: \r\n'
          '\t  NI\r\nMeio de Resp.: \r\n\t  E-MAIL\r\nObservações: \r\n'
          '\t  NÃO INFORMOU O PONTO DE REFERÊNCIA.')
out14 = ('Retirada de árvores As árvores estão destruindo a calçada.\r\n'
         '\r\nProtocolo: \r\n\t  \r\nSituação: \r\n\t  ABERTA\r\n'
         'Email: \r\n\t  \r\nData de Criação: \r\n\t   \r\n'
         '\r\n Dados do Assunto\r\nDescrição: \r\n\t  SOLICITA A RETIRADA '
         'DE DOIS ALFENEIROS DA VIA MENCIONADA. RELATA QUE ELES ESTÃO '
         'AFETANDO A TUBULAÇÃO DE GÁ E A CALÇADA ESTÁ TODA DANIFICADA. '
         'CIDADÃO RELATA QUE REFERENTE A ESTA SITUAÇÃO, JÁ FOI DADA '
         'ENTRADA NA RUA DA CIDADANIA DO PINHEIRINHO, UMA DAS DATAS DE '
         'ENTRADA É  COM O PARECER TÉCNICO:  E ELES '
         'ENCAMINHARAM PARA O HORTO MUNCIPAL. RELATA QUE ESTÁ UM JOGO DE '
         'EMPURRA EMPURRA, E NINGÚEM RESOLVE O PROBLEMA. PEDE VERIFICAÇÃO '
         'COM URGÊNCIA.\r\nAssunto: \r\n\t  ÁRVORE\r\nSubdivisão: \r\n'
         '\t  AVALIAÇÃO TÉCNICA - VIA PÚBLICA\r\nEndereço: \r\n\t\r\n'
         'Bairro: \r\n\t  AGUA VERDE\r\nRegional: \r\n\t  Unidade '
         'Regional Portao\r\nCep: \r\n\t  \r\nTransversal 1: \r\n'
         '\t  R. SANTA CATARINA\r\nTransversal 2: \r\n\t  R. RIO GRANDE '
         'DO SUL\r\nCidade: \r\n\t  CURITIBA -  PR\r\nPonto de Ref.: \r\n'
         '\t  NI\r\nMeio de Resp.: \r\n\t  E-MAIL\r\nObservações: \r\n'
         '\t  NÃO INFORMOU O PONTO DE REFERÊNCIA.')

desc15 = ('Resposta 156 insuficiente Prezados,\r\n\r\nSirvo-me do presente '
          'expediente para efetuar reclamação acerca do atendimento do '
          'relatado no protocolo 6140000 de 28/10/2015 - SOLICITA '
          'VERIFICAÇÃO QUANTO A EROSÃO EM GALERIAS DE ÁGUAS PLUVIAIS '
          'OCORRENDO NA ÁREA DE PASSEIO. DESCRIÇÃO DO CIDADÃO NA ÍNTEGRA: '
          'SRS. A CALÇADA QUE FICA AO LADO DO CONDOMÍNIO CEDEU, ABRINDO UM '
          'BURACO QUE DEIXA, INCLUSIVE, APARENTE A TUBULAÇÃO. PEDIMOS '
          'VISTORIA, HAJA VISTA QUE ESTÁ BEM AO LADO DA ENTRADA DA GARAGEM '
          'DO CONDOMÍNIO, PELO QUE CASO AUMENTE, IMPEDIRÁ QUE CARROS ENTREM '
          'NO CONDOMÍNIO.\r\n\r\nAntes de contactar a prefeitura municipal, '
          'havíamos solicitado reparos à SANEPAR, que informou não ser '
          'responsabilidade da mesma e sim da Prefeitura, conforme protocolo '
          'de 23/10:\r\n\r\n-------------------------------------------------'
          '----------------------------------------------\r\nEm atenção à '
          'solicitação encaminhada a Ouvidoria da Sanepar, apresentamos '
          'abaixo os devidos esclarecimentos:\r\n\r\nDe acordo com a resposta '
          'da área gestora, se trata de problema na galeria, pertinente a '
          'Prefeitura Municipal. Fiscal esteve no local hoje pela manhã e '
          'orientou o porteiro sobre o fato.\r\n\r\nAproveitamos para '
          'agradecer a oportunidade e lembrar que estamos a sua disposição.'
          '\r\n\r\nAtenciosamente,\r\n\r\nOuvidoria Sanepar.\r\n\r\nSegue '
          'abaixo os dados do seu protocolo:\r\n\r\n\r\nProtocolo: '
          'SN07113/2015-Q\tO que deseja: Reclamação\tMatricula: '
          '2651.6617\r\nCriado em: 23/10/2015\tNome: Condominio Ilha de '
          'Okinawa\r\nCidade: Curitiba\t\r\nAssunto: Recomposição / obras / '
          'limpeza\r\n\r\n---------------------------------------------------'
          '--------------------------------------------\r\n\r\nOcorre que, em '
          'data de hoje (11/11) foi encaminhada resposta pela central 156, '
          'informando que o pleito foi remetido à SANEPAR - INFORMAMOS QUE A '
          'SOLICITAÇÃO FOI ENCAMINHADA PARA PROVIDÊNCIAS DA SANEPAR.\r\n\r\n'
          'Srs., solicitam-se providências para sanar o problema relatado, '
          'haja vista que fica em área de passeio, mas na saída da garagem do '
          'condomínio e, a cada dia, o terreno cede mais, com risco aos carros '
          'que ali transitam.\r\n\r\nInformo ainda que esta ocorrência não é '
          'inédita, e já foi objeto de solicitação anterior junto à PMC em '
          'outra oportunidade (PROTOCOLO - 00305972i - 14/11/2014) no que '
          'fomos atendidos.\r\n\r\nSolicitou-se ainda que seja feito um '
          'trabalho para saneamento definitivo do problema, pois do contrário, '
          'a cada chuva mais forte, o terreno novamente cede, e temos que '
          'ficar meses aguardando as providências paliativas do poder público. '
          '\r\n\r\n\r\n\r\n-- \r\nCordialmente,\r\n\r\nRafael Corrêa da '
          'Cunha\r\nSíndico\r\n(41) 9192-0021')
out15 = ('Resposta 156 insuficiente Prezados,\r\n\r\nSirvo-me do presente '
         'expediente para efetuar reclamação acerca do atendimento do '
         'relatado no protocolo  de  - SOLICITA '
         'VERIFICAÇÃO QUANTO A EROSÃO EM GALERIAS DE ÁGUAS PLUVIAIS '
         'OCORRENDO NA ÁREA DE PASSEIO. DESCRIÇÃO DO CIDADÃO NA ÍNTEGRA: '
         'SRS. A CALÇADA QUE FICA AO LADO DO CONDOMÍNIO CEDEU, ABRINDO UM '
         'BURACO QUE DEIXA, INCLUSIVE, APARENTE A TUBULAÇÃO. PEDIMOS '
         'VISTORIA, HAJA VISTA QUE ESTÁ BEM AO LADO DA ENTRADA DA GARAGEM '
         'DO CONDOMÍNIO, PELO QUE CASO AUMENTE, IMPEDIRÁ QUE CARROS ENTREM '
         'NO CONDOMÍNIO.\r\n\r\nAntes de contactar a prefeitura municipal, '
         'havíamos solicitado reparos à SANEPAR, que informou não ser '
         'responsabilidade da mesma e sim da Prefeitura, conforme protocolo '
         'de :\r\n\r\n-------------------------------------------------'
         '----------------------------------------------\r\nEm atenção à '
         'solicitação encaminhada a Ouvidoria da Sanepar, apresentamos '
         'abaixo os devidos esclarecimentos:\r\n\r\nDe acordo com a resposta '
         'da área gestora, se trata de problema na galeria, pertinente a '
         'Prefeitura Municipal. Fiscal esteve no local hoje pela manhã e '
         'orientou o porteiro sobre o fato.\r\n\r\nAproveitamos para ' 
         'agradecer a oportunidade e lembrar que estamos a sua disposição.'
         '\r\n\r\nAtenciosamente,\r\n\r\nOuvidoria Sanepar.\r\n\r\nSegue '
         'abaixo os dados do seu protocolo:\r\n\r\n\r\nProtocolo: '
         '\tO que deseja: Reclamação\tMatricula: '
         '\r\nCriado em: \tNome: Condominio Ilha de '
         'Okinawa\r\nCidade: Curitiba\t\r\nAssunto: Recomposição / obras / '
         'limpeza\r\n\r\n---------------------------------------------------'
         '--------------------------------------------\r\n\r\nOcorre que, em '
         'data de hoje () foi encaminhada resposta pela central 156, '
         'informando que o pleito foi remetido à SANEPAR - INFORMAMOS QUE A '
         'SOLICITAÇÃO FOI ENCAMINHADA PARA PROVIDÊNCIAS DA SANEPAR.\r\n\r\n'
         'Srs., solicitam-se providências para sanar o problema relatado, '
         'haja vista que fica em área de passeio, mas na saída da garagem do '
         'condomínio e, a cada dia, o terreno cede mais, com risco aos carros '
         'que ali transitam.\r\n\r\nInformo ainda que esta ocorrência não é '
         'inédita, e já foi objeto de solicitação anterior junto à PMC em '
         'outra oportunidade (PROTOCOLO -  - ) no que '
         'fomos atendidos.\r\n\r\nSolicitou-se ainda que seja feito um '
         'trabalho para saneamento definitivo do problema, pois do contrário, '
         'a cada chuva mais forte, o terreno novamente cede, e temos que '
         'ficar meses aguardando as providências paliativas do poder público. '
         '\r\n\r\n\r\n\r\n-- \r\nCordialmente,\r\n\r\nRafael Corrêa da '
         'Cunha\r\nSíndico\r\n')

desc16 = ('ILUMINAÇÃO PÚBLICA ,SEM RETORNO Boa tarde senhores da Ouvidoria '
          'Municipal,\r\n\r\nA reclamação abaixo segue na integra a '
          'registrada por quatro vezes no serviço 156 desde o dia '
          '03/11/2015 sem nenhuma resposta plausível:\r\n\r\nHOJE JÁ É '
          '01/12/2015 E A LUMINÁRIA DO POSTE CONTINUA APAGADA. ESTAMOS '
          'AGUARDANDO MANUTENÇÃO E ATÉ O MOMENTO O REGISTRO CONSTA EM '
          'ABERTO SEM RESPOSTA DO QUE ESTA ACONTECENDO.SEGUE NÚMEROS DOS '
          'REGISTRO FEITOS ATÉ AGORA POREM SEM RESPOSTA OU SOLUÇÃO DO '
          'PROBLEMA. POR FAVOR VERIFIQUEM OS MOTIVOS E NOS INFORMEM. '
          'PROTOCOLO SOLICITADO PELA INTERNET DE NÚMERO : 356352I, GEROU '
          'A SOLICITAÇÃO DE NÚMERO 6145459, QUE FOI CRIADA NA DATA '
          '03/11/2015 E TEM O SEGUINTE ASSUNTO: \r\n\r\nILUMINAÇÃO '
          'PÚBLICA - MANUTENÇÃO DE LUMINÁRIAS. SOLICITA A TROCA DE '
          'LÂMPADA QUEIMADA. SEGUE DESCRIÇÃO. "SOLICITO AO DEPARTAMENTO '
          'DE ILUMINAÇÃO PÚBLICA A MANUTENÇÃO OU TROCA DE UMA LAMPADA '
          'QUE FICA LOCALIZADO: FRENTE AO SOBRADO 2425-5 E SOBRADO EM '
          'FRENTE 2400 NA RUA:CRISTIANO STROBEL – PLACA AZUL NO BRAÇO '
          'DA LUMIÁRIA: EMl - CAD. \r\nPONTO DE REFERENCIA 50/100 '
          'METROS DA PANIFICADORA STROBEL, O  LOCAL A NOITE FICA MUITO '
          'ESCURO OFERECENDO RISCOS DE SEGURANÇA AS RESIDÊNCIAS EM TODO '
          'O PERÍMETRO QUE ABRANGE A ILUMINAÇÃO DESSE POSTE DE LUZ. '
          '\r\n\r\nO 156 não funciona não é dado o devido retorno do que '
          'acontece. Nesse caso é lâmpada queimada,é problema nos fios '
          'de luz do poste???? ... Cadê o Prefeito  e as equipes de '
          'serviços dessa cidade?\r\n\r\nSegue os números de protocolo '
          'até o momento REGISTRADOS: 356352i, 357087i, 358417i 361482i '
          '\r\n\r\nFico no aguardo do retorno de como será resolvido ou '
          'se não for resolvido porque não foi ... Caso não se tenha a '
          'solução peço que me informem qual é uma outra opção,Mídia,'
          'TV?\r\n\r\nAss.Robson Borges.\r\n41-99770062')
out16 = ('ILUMINAÇÃO PÚBLICA ,SEM RETORNO Boa tarde senhores da Ouvidoria '
         'Municipal,\r\n\r\nA reclamação abaixo segue na integra a '
         'registrada por quatro vezes no serviço 156 desde o dia '
         ' sem nenhuma resposta plausível:\r\n\r\nHOJE JÁ É '
         ' E A LUMINÁRIA DO POSTE CONTINUA APAGADA. ESTAMOS '
         'AGUARDANDO MANUTENÇÃO E ATÉ O MOMENTO O REGISTRO CONSTA EM '
         'ABERTO SEM RESPOSTA DO QUE ESTA ACONTECENDO.SEGUE NÚMEROS DOS '
         'REGISTRO FEITOS ATÉ AGORA POREM SEM RESPOSTA OU SOLUÇÃO DO '
         'PROBLEMA. POR FAVOR VERIFIQUEM OS MOTIVOS E NOS INFORMEM. '
         'PROTOCOLO SOLICITADO PELA INTERNET DE NÚMERO : , GEROU '
         'A SOLICITAÇÃO DE NÚMERO , QUE FOI CRIADA NA DATA '
         ' E TEM O SEGUINTE ASSUNTO: \r\n\r\nILUMINAÇÃO '
         'PÚBLICA - MANUTENÇÃO DE LUMINÁRIAS. SOLICITA A TROCA DE '
         'LÂMPADA QUEIMADA. SEGUE DESCRIÇÃO. "SOLICITO AO DEPARTAMENTO '
         'DE ILUMINAÇÃO PÚBLICA A MANUTENÇÃO OU TROCA DE UMA LAMPADA '
         'QUE FICA LOCALIZADO: FRENTE AO SOBRADO  E SOBRADO EM '
         'FRENTE  NA RUA:CRISTIANO STROBEL – PLACA AZUL NO BRAÇO '
         'DA LUMIÁRIA: EMl - CAD. \r\nPONTO DE REFERENCIA  '
         'METROS DA PANIFICADORA STROBEL, O  LOCAL A NOITE FICA MUITO '
         'ESCURO OFERECENDO RISCOS DE SEGURANÇA AS RESIDÊNCIAS EM TODO '
         'O PERÍMETRO QUE ABRANGE A ILUMINAÇÃO DESSE POSTE DE LUZ. '
         '\r\n\r\nO 156 não funciona não é dado o devido retorno do que '
         'acontece. Nesse caso é lâmpada queimada,é problema nos fios '
         'de luz do poste???? ... Cadê o Prefeito  e as equipes de '
         'serviços dessa cidade?\r\n\r\nSegue os números de protocolo '
         'até o momento REGISTRADOS: , ,   '
         '\r\n\r\nFico no aguardo do retorno de como será resolvido ou '
         'se não for resolvido porque não foi ... Caso não se tenha a '
         'solução peço que me informem qual é uma outra opção,Mídia,'
         'TV?\r\n\r\nAss.Robson Borges.\r\n')

desc17 = ('alteracao dados carnet IPTU comprei um apartamento com garagem '
          'em Curitiba há 3 anos  e paguei o ITBI, estranhei que no ano '
          'seguinte o carnet do IPTU veio com o nome do antigo proprietário, '
          'entrei em contato com a prefeitura e me informaram que eu é '
          'que deveria comprovar a transferência e pediram para enviar por '
          'e-mail cópia da escritura, e eu fiz, este ano recebi os carnet do '
          'IPTU, alteraram somente o carnet do apartamento e da garagem '
          'continua em nome do antigo proprietário, em qualquer órgão ou '
          'cidade do Brasil, se você paga a taxa ou imposto de '
          'transferência automaticamente os documentos vem em nome do atual '
          'proprietário. Número da inscrição fiscal 14-007-001.004-5 e '
          '14-007-001.022-3')
out17 = ('alteracao dados carnet IPTU comprei um apartamento com garagem '
         'em Curitiba há 3 anos  e paguei o ITBI, estranhei que no ano '
         'seguinte o carnet do IPTU veio com o nome do antigo proprietário, '
         'entrei em contato com a prefeitura e me informaram que eu é '
         'que deveria comprovar a transferência e pediram para enviar por '
         'e-mail cópia da escritura, e eu fiz, este ano recebi os carnet do '
         'IPTU, alteraram somente o carnet do apartamento e da garagem '
         'continua em nome do antigo proprietário, em qualquer órgão ou '
         'cidade do Brasil, se você paga a taxa ou imposto de '
         'transferência automaticamente os documentos vem em nome do atual '
         'proprietário. Número da inscrição fiscal  e ')

desc18 = ('Troca de lampada bom dia!!\r\n\r\nNo dia 18/01 abri um chamado '
          'para troca de lampada e até o momento não tivemos retorno '
          'nenhum, quanto tempo é preciso para Prefeitura trocar uma '
          'lampada? Esta lampada já esta "queimada" uns 03 meses e com '
          'certeza outros moradores já ligaram para fazer a troca e até '
          'agora nada.\r\n\r\nobs.: nº do protocolo do 156 - 006252690 '
          '- Rua Tele Santana da Silva, 439 - Cachoeira - 82220-418.')
out18 = ('Troca de lampada bom dia!!\r\n\r\nNo dia  abri um chamado '
         'para troca de lampada e até o momento não tivemos retorno '
         'nenhum, quanto tempo é preciso para Prefeitura trocar uma '
         'lampada? Esta lampada já esta "queimada" uns 03 meses e com '
         'certeza outros moradores já ligaram para fazer a troca e até '
         'agora nada.\r\n\r\nobs.: nº do protocolo do 156 -  '
         '- Rua Tele Santana da Silva, 439 - Cachoeira - .')

desc19 = (
    'providenciar algo mais efeitovo'
    'Moro há mais de 45 anos no endereço rua dr. ovande do amaral, 86, em frente '
    'à  entrada e saída do hospital erasto gaertner no bairro jardim das americas '
    'cep81520-060. casa de esquina c a romano fressato. Geramos já 450 protocolos '
    'comprovados de pedido de fiscalização do setram , pois todos os dias há '
    'inadimplências no meu endereço que já há faixa amarela em toda extensão '
    'rente à calçada no meu endereço e há placa de proibido parar, mas mesmo '
    'assim todos os dias os carros não respeitam a sinalização apenas, aí com o '
    'tempo de tanto ter que ligar p 156 pedido o setram que por vezes nao vem e '
    'quando vem autua vários carros, mas há rodízios de parada de veículos '
    'incomodam muito minha residência, com perturbaçoes de vcopnversas altas os '
    'carros que ficam os motoristas esperando todos fazerem tratamento no '
    'hospital param e ficam jogando lixo na minha grama algazarras e lixos e até '
    'urinam na frente do meu portão. Como tenhoque chamar todos os dias o setram, '
    'e muitas vezes várias vezes no mesmo dia, isso quanod o setram vem, e quanod '
    'nao vem ficamos à mercê do mal comportamento de motoristas mal educados eque '
    'estacionam horas sobre a faixa amarela e naõ estão nem ai com a sinalização. '
    'Peço e já havia pedido por favor que colocassem obstáculos em cima da faixa '
    'amarela obstruindo realmente a parada desses infligentes, poois sem como '
    'estacionar seria muito melhor para todos. Mas já ahvia pedido mas disseram '
    'que nao poderiam colocar obstáculo... então eu tenho que ligar diversas  '
    'vezes por dia todos os dias o tempo inteiro com esses motoristas mal '
    'educados, param muito ônibus de outros municipios que vem trazer pessoas no '
    'hospital e por minha residência ser bem na frente da entrada do mesmo, fico '
    'sendo a mais prejudicada de todos, pagamos impostos de casa de esquina caro, '
    'para termos que nos incomodar, pois seestá havendo dezenas de solicitações '
    'de setram p/ auturarem os veículos, porque noa tomam um atitude mais '
    'efetiva, colocando obstaculos rente a minha calçada impossibilitando a '
    'parada desses motoristas inadimplentes??? muitas vezes também nao pude '
    'entrar na minha residencia e nem sair, por carros mal edcuados pararemmbem '
    'na entrada da minha garagem, já deixei de sair por nao poder tirar o carro '
    'da garagem e já fiquei mais 3 horas noa noite sem poder entrar por pararem '
    'na minha guia rebaixada pois moramos na frente deste hospital erasto '
    'gaertner, e mesmo que na minha garagem tem placa de garagem proibido '
    'estaciuonar e parar e tem poste com luz bem nitida a guia rebaixada e tanto '
    'na linha amrarela quanto na guia rebaixada eles nao se intimidam, e quanod '
    'ligamos as vezes na noite p entrarmos em casa p o 156 demoram p atender e as '
    'vezes o setram nem vai na hora demora umas duas e as vezes nao comparecem, e '
    'nao tem guincho para tirar o veiculo estacionado irregularmente.... pelo '
    'encarecidamente com urngencia provid~encias no meu endreço que faça a '
    'REPINTURA AMARELA em frente ao meu endereço e obstaculo em cima beirando a '
    'calaçada pegando toda extensão da casa claçada POR FAVOR estamos ficando '
    'doentes, pelo descaso e todos os dias passar estress por negligencia de quem '
    'estrutura a sinalização, por favor coloquem obstaculos em cima da faixa '
    'amarela em frente ao meu endereço beirando a calçada nao no meio da rua '
    'allooooo, senao ainda vao fazer coisas nos prejudiquem mais ainda. Se caso '
    'nao ouver uma solução eu vou à imprensa reclamar e filmaremos na tv rpc e '
    'outras emissoras o descaso compliotamente há nos desse pedido simples, já '
    'não d´amais para aguentar motristas mal educados. Aguardo providencias '
    'urgentee nao mais respostas vagas e negativas, quero ação objetiva, pois há '
    'pouco tempo repintaram nessa mesma rua mais para cima onde não há '
    'necessidade, há necessidade repintura urgente na frente da minha e '
    'obstaculos em cima senão nao resolverá nada. faz anos essess trantornos, nao '
    'aguentamos mais, vamos agir por lei e imprensa,.')
out19 = (
    'providenciar algo mais efeitovo'
    'Moro há mais de 45 anos no endereço rua dr. ovande do amaral, 86, em frente '
    'à  entrada e saída do hospital erasto gaertner no bairro jardim das americas '
    'cep. casa de esquina c a romano fressato. Geramos já 450 protocolos '
    'comprovados de pedido de fiscalização do setram , pois todos os dias há '
    'inadimplências no meu endereço que já há faixa amarela em toda extensão '
    'rente à calçada no meu endereço e há placa de proibido parar, mas mesmo '
    'assim todos os dias os carros não respeitam a sinalização apenas, aí com o '
    'tempo de tanto ter que ligar p 156 pedido o setram que por vezes nao vem e '
    'quando vem autua vários carros, mas há rodízios de parada de veículos '
    'incomodam muito minha residência, com perturbaçoes de vcopnversas altas os '
    'carros que ficam os motoristas esperando todos fazerem tratamento no '
    'hospital param e ficam jogando lixo na minha grama algazarras e lixos e até '
    'urinam na frente do meu portão. Como tenhoque chamar todos os dias o setram, '
    'e muitas vezes várias vezes no mesmo dia, isso quanod o setram vem, e quanod '
    'nao vem ficamos à mercê do mal comportamento de motoristas mal educados eque '
    'estacionam horas sobre a faixa amarela e naõ estão nem ai com a sinalização. '
    'Peço e já havia pedido por favor que colocassem obstáculos em cima da faixa '
    'amarela obstruindo realmente a parada desses infligentes, poois sem como '
    'estacionar seria muito melhor para todos. Mas já ahvia pedido mas disseram '
    'que nao poderiam colocar obstáculo... então eu tenho que ligar diversas  '
    'vezes por dia todos os dias o tempo inteiro com esses motoristas mal '
    'educados, param muito ônibus de outros municipios que vem trazer pessoas no '
    'hospital e por minha residência ser bem na frente da entrada do mesmo, fico '
    'sendo a mais prejudicada de todos, pagamos impostos de casa de esquina caro, '
    'para termos que nos incomodar, pois seestá havendo dezenas de solicitações '
    'de setram p/ auturarem os veículos, porque noa tomam um atitude mais '
    'efetiva, colocando obstaculos rente a minha calçada impossibilitando a '
    'parada desses motoristas inadimplentes??? muitas vezes também nao pude '
    'entrar na minha residencia e nem sair, por carros mal edcuados pararemmbem '
    'na entrada da minha garagem, já deixei de sair por nao poder tirar o carro '
    'da garagem e já fiquei mais 3 horas noa noite sem poder entrar por pararem '
    'na minha guia rebaixada pois moramos na frente deste hospital erasto '
    'gaertner, e mesmo que na minha garagem tem placa de garagem proibido '
    'estaciuonar e parar e tem poste com luz bem nitida a guia rebaixada e tanto '
    'na linha amrarela quanto na guia rebaixada eles nao se intimidam, e quanod '
    'ligamos as vezes na noite p entrarmos em casa p o 156 demoram p atender e as '
    'vezes o setram nem vai na hora demora umas duas e as vezes nao comparecem, e '
    'nao tem guincho para tirar o veiculo estacionado irregularmente.... pelo '
    'encarecidamente com urngencia provid~encias no meu endreço que faça a '
    'REPINTURA AMARELA em frente ao meu endereço e obstaculo em cima beirando a '
    'calaçada pegando toda extensão da casa claçada POR FAVOR estamos ficando '
    'doentes, pelo descaso e todos os dias passar estress por negligencia de quem '
    'estrutura a sinalização, por favor coloquem obstaculos em cima da faixa '
    'amarela em frente ao meu endereço beirando a calçada nao no meio da rua '
    'allooooo, senao ainda vao fazer coisas nos prejudiquem mais ainda. Se caso '
    'nao ouver uma solução eu vou à imprensa reclamar e filmaremos na tv rpc e '
    'outras emissoras o descaso compliotamente há nos desse pedido simples, já '
    'não d´amais para aguentar motristas mal educados. Aguardo providencias '
    'urgentee nao mais respostas vagas e negativas, quero ação objetiva, pois há '
    'pouco tempo repintaram nessa mesma rua mais para cima onde não há '
    'necessidade, há necessidade repintura urgente na frente da minha e '
    'obstaculos em cima senão nao resolverá nada. faz anos essess trantornos, nao '
    'aguentamos mais, vamos agir por lei e imprensa,.')

desc20 = (
    'reclamação iluminação pública'
    'Conforme reclamações realizadas protocolo nº 6188784 e 6188785, informo q só '
    'foi feita o reparo da lâmpada na rua Pedro Antonio da Costa, porém a da rua '
    'Fernando de Noronha não foi realizada até o momento, sem passaram 3 meses e '
    'nada, conforme dados já protocolado do poste anteriormente, informo q o '
    'poste fica em frente ao número 1852 da rua Fernando de Noronha, ao lado do '
    'mercado Califórnia, de frente ao início da rua Pedro Antonio da Costa.\r\n'
    '              Espero q o serviço seja realizado com a maior brevidade '
    'possível, pois muitas pessoas passam sufoco por ser um lugar ermo, sujeito a '
    'assaltos e tropeços na calçada, como já aconteceu com meu sogro, afinal o '
    'valor q pagamos mensalmente não é nada barato.\r\n'
    '\r\n'
    'No aguardo,\r\n'
    '\r\n'
    'Josimar Sampaio\r\n'
    '41-8421-8859\r\n'
    '41-9692-5657')
out20 = (
    'reclamação iluminação pública'
    'Conforme reclamações realizadas protocolo nº  e , informo q só '
    'foi feita o reparo da lâmpada na rua Pedro Antonio da Costa, porém a da rua '
    'Fernando de Noronha não foi realizada até o momento, sem passaram 3 meses e '
    'nada, conforme dados já protocolado do poste anteriormente, informo q o '
    'poste fica em frente ao número  da rua Fernando de Noronha, ao lado do '
    'mercado Califórnia, de frente ao início da rua Pedro Antonio da Costa.\r\n'
    '              Espero q o serviço seja realizado com a maior brevidade '
    'possível, pois muitas pessoas passam sufoco por ser um lugar ermo, sujeito a '
    'assaltos e tropeços na calçada, como já aconteceu com meu sogro, afinal o '
    'valor q pagamos mensalmente não é nada barato.\r\n'
    '\r\n'
    'No aguardo,\r\n'
    '\r\n'
    'Josimar Sampaio\r\n'
    '\r\n')

desc21 = (' Tapa buraco'
          'Pedido feito no 156 em 08/12/2014-5679933, e outros três recentes: '
          '5678306.5678307,5678308.\r\n'
          '\r\n'
          'O pedido consta como  obra executada porém não foi feito. Regional do CIC')
out21 = (' Tapa buraco'
          'Pedido feito no 156 em , e outros três recentes: '
          ',.\r\n'
          '\r\n'
          'O pedido consta como  obra executada porém não foi feito. Regional do CIC')

desc22 = ('Troca de lâmpadas rede Pública'
    'Prezados,\r\n'
    'Em atenção a obrigação do Município trocar as lâmpadas da rede pública, já '
    'solicitamos por duas oportunidades há mais de 2 (dois) meses mediante o '
    'protocolos nos. 6158014 e 6182265 a substituição de 2 (duas) lâmpadas '
    'queimadas na via do Cond. Villagio di Roma, à R. José Tomasi, nº 142, Santa '
    'Felicidade.\r\n'
    'Já foram identificados os postes:\r\n'
    '- 21042009/600-1050/Postmar NXR-AE1\r\n'
    'Poste na frente do lote/casa 16\r\n'
    '- 1980106.300 DAN/VITTE\r\n'
    'Poste na frente do lote/casa 25\r\n'
    'O final do ano se aproxima e a insegurança aumenta com ausência de '
    'iluminação nas ruas.\r\n'
    'O Município de Curitiba não está atendendo as solicitações, um verdadeiro '
    'absurdo, pois existe contrato vigente com a administração para prestação '
    'desse serviço.\r\n'
    'Solicito providências e encaminhamentos urgente!\r\n'
    'Att.,\r\n'
    'Rômulo Bronzel\r\n'
    'Síndico do Condomínio Villagio di Roma')
out22 = ('Troca de lâmpadas rede Pública'
    'Prezados,\r\n'
    'Em atenção a obrigação do Município trocar as lâmpadas da rede pública, já '
    'solicitamos por duas oportunidades há mais de 2 (dois) meses mediante o '
    'protocolos nos.  e  a substituição de 2 (duas) lâmpadas '
    'queimadas na via do Cond. Villagio di Roma, à R. José Tomasi, nº 142, Santa '
    'Felicidade.\r\n'
    'Já foram identificados os postes:\r\n'
    '- -/Postmar \r\n'
    'Poste na frente do lote/casa 16\r\n'
    '-  DAN/VITTE\r\n'
    'Poste na frente do lote/casa 25\r\n'
    'O final do ano se aproxima e a insegurança aumenta com ausência de '
    'iluminação nas ruas.\r\n'
    'O Município de Curitiba não está atendendo as solicitações, um verdadeiro '
    'absurdo, pois existe contrato vigente com a administração para prestação '
    'desse serviço.\r\n'
    'Solicito providências e encaminhamentos urgente!\r\n'
    'Att.,\r\n'
    'Rômulo Bronzel\r\n'
    'Síndico do Condomínio Villagio di Roma')

desc23 = ('Duvida'
    'Bom dia,como contribuinte.\r\n'
    '\r\n'
    'Me recorro a  uma dívida .\r\n'
    '\r\n'
    'O veículo Sandero: cor branca,ano 2015/2016 -placa de Curitiba AZZ6594 '
    'pertence a frota de veículos da Câmara e é utilizado por um de seus '
    'membros?\r\n'
    '\r\n'
    'Informações a respeito diz que é um veículo locado.\r\n'
    '\r\n'
    'Minha dúvida é, se esse veículo é para ser utilizado em serviço ou '
    'também:sábado,domingo,feriados ou em qualquer horário.\r\n'
    '\r\n'
    'Ou somente para "uso exclusivo" em serviço,como todos veículo da esfera '
    'estadual e federal?\r\n'
    '\r\n'
    ' \r\n'
    '\r\n'
    'Obrigado,')
out23 = ('Duvida'
    'Bom dia,como contribuinte.\r\n'
    '\r\n'
    'Me recorro a  uma dívida .\r\n'
    '\r\n'
    'O veículo Sandero: cor branca,ano  -placa de Curitiba  '
    'pertence a frota de veículos da Câmara e é utilizado por um de seus '
    'membros?\r\n'
    '\r\n'
    'Informações a respeito diz que é um veículo locado.\r\n'
    '\r\n'
    'Minha dúvida é, se esse veículo é para ser utilizado em serviço ou '
    'também:sábado,domingo,feriados ou em qualquer horário.\r\n'
    '\r\n'
    'Ou somente para "uso exclusivo" em serviço,como todos veículo da esfera '
    'estadual e federal?\r\n'
    '\r\n'
    ' \r\n'
    '\r\n'
    'Obrigado,')


@pytest.mark.parametrize("test_input,expected", [
    (desc1, out1),
    (desc2, out2),
    (desc3, out3),
    (desc4, out4),
    (desc5, out5),
    (desc6, out6),
    (desc7, out7),
    (desc8, out8),
    (desc9, out9),
    (desc10, out10),
    (desc11, out11),
    (desc12, out12),
    (desc13, out13),
    (desc14, out14),
    (desc15, out15),
    (desc16, out16),
    (desc17, out17),
    (desc18, out18),
    (desc19, out19),
    (desc20, out20),
    (desc21, out21),
    (desc22, out22),
    (desc23, out23),
])

def test_eval(test_input, expected):
    assert remove_unwanted_patterns(test_input) == expected
