l = ['$',
 '%',
 '&',
 '&utm_campaign=share_for_starters_page&utm_term=des',
 '&utm_source=share_petition&utm_medium=',
 '03',
 '1',
 '105',
 '118',
 '155',
 '156',
 '156 esgotaram',
 '156 insuficiente',
 '156 prefeitura',
 '2',
 '246',
 '254',
 '265',
 '269',
 '3',
 '325',
 '343',
 '360',
 '4',
 '5',
 '520',
 '561',
 '568',
 '580',
 '640',
 '72',
 '721',
 '722',
 '858',
 '859',
 '915',
 '92',
 '98',
 '<',
 '= “',
 '=cj0o1fnxvn4',
 '=punrdomyf_w',
 '>',
 'a',
 'a15',
 'a3y',
 'a7am',
 'abandono',
 'abordagem',
 'abrigo',
 'absurdamente',
 'abusiva',
 'abusivo',
 'acabando',
 'acatada',
 'acatou',
 'acendia',
 'acessarem',
 'acesso',
 'achando',
 'acontecidos',
 'aconteçe nes',
 'acreditem',
 'acréscimo',
 'acústico',
 'adequacao',
 'adequá',
 'adicional',
 'administração',
 'administração municipal',
 'administração pífia',
 'administração pública',
 'admissivel',
 'aedes',
 'aedes aegypti',
 'agendamento',
 'agente',
 'agente comunitario',
 'agente público',
 'agente setran',
 'agente setran novena',
 'agentes',
 'agentes públicos',
 'agilizem',
 'agravantes',
 'agua',
 'aguardam',
 'aguardasse',
 'aguente',
 'ah4',
 'ajv',
 'alceu',
 'alcoólica',
 'alertando',
 'algo',
 'alguma',
 'alguma coisa',
 'alguma tragedia',
 'alimentar',
 'alteracao',
 'alusiva',
 'alvara',
 'alvaro',
 'alvará',
 'alvará comercial',
 'aly',
 'ambiente',
 'ameaça',
 'amiguinhos',
 'ampla',
 'amplo',
 'amplos',
 'amrela',
 'andares',
 'andrea',
 'anestesiologista',
 'anexado',
 'angustiante',
 'anoitecer',
 'anr',
 'ante',
 'antes',
 'anti',
 'antigas',
 'antigas travessias elevadas',
 'antipó',
 'anunciada',
 'anunciado',
 'apagam',
 'apagava',
 'aplicacoes',
 'aplicar',
 'aplicativo',
 'apontado',
 'aposentado',
 'aposto',
 'apresentados',
 'aquela',
 'aquela rua',
 'aqueles',
 'aquilo',
 'aquilo tratava',
 'ar1',
 'archibano voltolini',
 'argumenta',
 'armada',
 'armario',
 'armazem',
 'arranhões',
 'arruamento',
 'arrume',
 'arrumem',
 'aru',
 'ascendem',
 'asfaltadas',
 'asfaltamento',
 'asfalto',
 'asfalto nestas',
 'asfato',
 'asfáltica',
 'assador',
 'assaltado',
 'assassinato',
 'assessoramento juridico',
 'assis',
 'assunto',
 'atenderem',
 'atendeu',
 'atendeu mal',
 'atendiam',
 'atendida',
 'atendida troca',
 'atendimento',
 'atendimento #',
 'atendimento 156',
 'atendimento central 156',
 'atendimento durava',
 'atendimento prefeitura',
 'atendimento prioritario',
 'atendimento rua',
 'atendimento setran',
 'atendê',
 'athayde',
 'atletas',
 'atraso',
 'atrasos',
 'atrasos linha',
 'atraz',
 'atropela',
 'atropelada',
 'atualizações',
 'avisei',
 'avó',
 'avós',
 'b1xage\r\nb1xae8',
 'bahr',
 'baixios',
 'baixá',
 'bala',
 'baldio',
 'baldios',
 'bandeira',
 'barclaymore',
 'barulho',
 'bco',
 'beach',
 'bebe pequeno',
 'bebida',
 'bebida alcoólica',
 'bebidas',
 'bebidas alcoólicas',
 'bianco',
 'bicicleta',
 'bicicletas',
 'bicicletas\r\nmeio',
 'bicieta',
 'biológico',
 'bloqueio',
 'bloquinhos',
 'boleto',
 'boletos',
 'bons modos',
 'boq',
 'brasileiros',
 'brincadeira',
 'bronquite aguda',
 'bsr',
 'bss',
 'bueiros',
 'bulling',
 'buraco',
 'buracos',
 'buscasse',
 'bxf',
 'básica',
 'cabeça',
 'cabide',
 'cabos',
 'cachorros',
 'cada',
 'cada fiscalização',
 'cada veículo',
 'cadeirante',
 'caixa',
 'caixa captação',
 'caixa econômica',
 'calaçada',
 'calcadas',
 'caldeira',
 'cale',
 'caliça',
 'caliças',
 'calçada',
 'calçada destinada',
 'calçada podendo',
 'calçadões',
 'campina',
 'canaleta',
 'cancha',
 'caneta',
 'capazes',
 'capivara',
 'captação',
 'carater',
 'carrefour',
 'caus',
 'cavo',
 'caótico',
 'cedca',
 'ceder',
 'celepar',
 'celeridade',
 'celular',
 'centra 156',
 'centra156',
 'central',
 'central\r\n156',
 'central 156',
 'central f156',
 'central156',
 'centrel 156',
 'cercas elétricas',
 'certinho',
 'cgu',
 'chancelado',
 'change',
 'chega',
 'chegada',
 'chegado',
 'chegávamos',
 'chicletes',
 'chorar',
 'ciclistas',
 'ciclo',
 'ciclovias',
 'ciclísticos',
 'circo',
 'circunstanciado',
 'clandestino',
 'clínico',
 'cmc',
 'cmeis',
 'cohab',
 'coisa',
 'coisa destas',
 'coisa enquanto',
 'coisas',
 'coisinhas',
 'coitado daquelas',
 'colados',
 'coleta',
 'coleta caliça',
 'coleta resíduos vegetais',
 'coleta vegetal',
 'coleta •',
 'colisão',
 'coloca',
 'coloco',
 'colombo',
 'comendo',
 'comercial',
 'comercializou',
 'começar',
 'comparecemos',
 'comparecer',
 'competencia',
 'completa desconsideração',
 'completando',
 'compromete',
 'comprometimento',
 'computador',
 'comuniquei',
 'comupa',
 'conceda',
 'concretar',
 'concursos',
 'condutor',
 'condutora',
 'conduzir',
 'condução',
 'condôminio',
 'cone',
 'conexão',
 'confere',
 'conforto',
 'conseguiram coisa alguma',
 'consiga',
 'constatei',
 'constatou',
 'constavam',
 'construção',
 'construção irregular',
 'consulta',
 'consumo',
 'contamos',
 'contatar',
 'contento',
 'contibuição',
 'continham',
 'contribuo',
 'contudo',
 'contágios',
 'convencional',
 'conversando',
 'conversão',
 'copia',
 'corpos',
 'correr',
 'corrido',
 'corrimão',
 'corta',
 'corte',
 'cortês',
 'cosnta',
 'covarde',
 'cpom',
 'criadora',
 'criam',
 'crime',
 'criou',
 'critério',
 'crm',
 'croserias',
 'ct',
 'cuidando',
 'curitba urbs',
 'curitiba',
 'curriculum',
 'custos',
 'cães',
 'cônsul',
 'da',
 'dando',
 'daquele',
 'data',
 'de',
 'decorrência',
 'defeito',
 'deferido',
 'deficientes',
 'define',
 'deixa',
 'deixamos',
 'delas',
 'delegacia',
 'demarcações',
 'demasiada',
 'demolição',
 'demora',
 'demora atendimento',
 'demostrou',
 'denatran',
 'denge',
 'dengue',
 'denominada 3y',
 'depacote 1comprimido',
 'dependente',
 'desarrazoados',
 'desativados',
 'descasos',
 'descontamento',
 'descortesia',
 'descumpri',
 'desempenho',
 'desempregada',
 'desempregi',
 'deslocando',
 'desmotiva',
 'desnecessários',
 'desorganizar',
 'despropositada',
 'despropósito',
 'desprotegidos',
 'desqualifica',
 'desrespeitados',
 'dessas',
 'destaco',
 'destas',
 'destruindo',
 'determinados',
 'deva',
 'deve',
 'devem',
 'devendo',
 'deverá',
 'deverão',
 'devia',
 'dezoito',
 'dia',
 'diabetes',
 'dificultar',
 'difilcudadesfinanceiras',
 'diminuiu',
 'direitinho',
 'diretran',
 'diretriz',
 'disponho',
 'disponibilização',
 'disposiçao',
 'disse',
 'disso',
 'disto',
 'distribuição',
 'dividida',
 'divulgaram',
 'dizem',
 'documentação',
 'documentações',
 'documento',
 'documentos',
 'doe',
 'domicílios',
 'dores',
 'dose',
 'drenagem',
 'droga',
 'drogados',
 'drogar',
 'drogas',
 'drogas utilizem',
 'duplo',
 'duvidam',
 'dês',
 'e',
 'edificação',
 'efeitovo',
 'efetuaram',
 'eficazes',
 'electrolux',
 'eleições',
 'eleronica',
 'eletivas',
 'eletrica',
 'eletronico',
 'elevado',
 'emaranhado',
 'embargá',
 'emergencia',
 'encarregados',
 'encontra',
 'encontram',
 'encontramos',
 'encontrava',
 'enganada',
 'engatinhando',
 'enquadramento',
 'enquanto',
 'enquanto agente',
 'enquanto isto',
 'ente público',
 'ente querido',
 'entende',
 'entram',
 'entrasse',
 'entregado',
 'entregando',
 'entregar',
 'entregarem',
 'erosão',
 'erosão formou',
 'ervas daninhas',
 'escada',
 'escadaria',
 'escadarias',
 'escolhido anterioremente',
 'escorregou',
 'escrocaro',
 'escuridao',
 'esmeralda',
 'especifique',
 'esperaram',
 'espeto',
 'esporadicamente achando',
 'esporte',
 'esportes',
 'esportiva',
 'estabelecer',
 'estabelecimento',
 'estabelecimento comercial',
 'estabelecimento inregular',
 'estabilizador',
 'estacionandos',
 'estacione',
 'estariam',
 'estarão',
 'estas',
 'estas caliças',
 'estas linhas',
 'estas vagas',
 'estimulará',
 'estragos',
 'estragou',
 'estranhamente',
 'estrategica',
 'estrutura',
 'estupro',
 'estupros',
 'estádios',
 'estávamos',
 'etapa',
 'etapas',
 'eucaliptos',
 'evita',
 'ewerton',
 'exata',
 'excelencias',
 'exceto',
 'exemplar',
 'exigir',
 'exoneração',
 'experimentar',
 'expiração',
 'explica',
 'explicito',
 'expressar',
 'expresso',
 'externar',
 'extingua',
 'extravasamento',
 'fa%c',
 'faculta',
 'facultado',
 'fala',
 'falecimento',
 'falta',
 'falta atendimento setran',
 'falta transparência nestas',
 'faltaram',
 'farol',
 'fas',
 'favorecidos',
 'faz',
 'faze',
 'fazê',
 'faíscas',
 'feitas',
 'ferreiro',
 'festa',
 'festa junina',
 'fez',
 'ficais',
 'ficalização',
 'ficara vendo outras',
 'filoso huberto rodhen',
 'fiscalizacao',
 'fiscalizando',
 'fiscalizaçao',
 'fiscalização',
 'fiscalização alguma',
 'fiscalização alvará',
 'fiscalização setran',
 'fiscalizações',
 'fixos',
 'flagrei',
 'foco',
 'focos',
 'focos dengue',
 'folclore',
 'folhas',
 'folhas resultantes',
 'fones',
 'for',
 'formalizar',
 'formou',
 'formuladas',
 'fornecê',
 'fossem',
 'fossem feitas fiscalizações',
 'fossem regularizadas',
 'fotocélula',
 'fraca',
 'fragilidade',
 'francieli',
 'franscica',
 'franscisco haneman',
 'freezer',
 'frequente',
 'frágeis',
 'funcionalismo',
 'funcionarios publicos',
 'funcionário',
 'funcionário público',
 'funeral',
 'furar',
 'furtado',
 'futebol',
 'futevôlei',
 'físicas',
 'gaeco',
 'gahos',
 'galeria',
 'galho',
 'galhos',
 'galhos desmoronando',
 'galhos invadiram terreno',
 'galhos árvore',
 'galões',
 'ganho',
 'garantam',
 'garantindo',
 'gasparini',
 'geladeira',
 'gerir',
 'gestão',
 'gestão municipal',
 'gestão pública',
 'goo',
 'grande',
 'grande\r\nmeio',
 'grande erosão',
 'grandes',
 'gratificação',
 'gratuidade',
 'gravado',
 'grosso',
 'grátis',
 'guarda',
 'guarda municipal',
 'guardas',
 'guardas municipais',
 'guido',
 'h1n1',
 'habilitacao',
 'habilitaçao',
 'habitacionais',
 'habitação popular',
 'hanemam',
 'hasteamento',
 'havro',
 'hidrometro',
 'hidrometro inexistente',
 'hipermercado',
 'hipermercado condor',
 'hn1',
 'holerite',
 'horror',
 'hospital',
 'humanidade',
 'humilham aqueles',
 'i',
 'ics',
 'idade',
 'identificando',
 'ifigênia',
 'ignorando',
 'illuminação pública',
 'iluminacão',
 'iluminacão pública',
 'iluminando',
 'iluminaria',
 'iluminaçao',
 'iluminação',
 'iluminação contratou',
 'iluminação demora',
 'iluminação lâmpada queimada',
 'iluminação manutenção',
 'iluminação pùblica',
 'iluminação pública',
 'iluminação pública manutenção',
 'iluminação pública queimada',
 'iluminição pública manutenção',
 'iluminção pública',
 'iluninação',
 'ilustre',
 'ilustríssimos',
 'imap',
 'imensos',
 'imiscuir',
 'impedi',
 'implantadas',
 'implantação',
 'impor',
 'importados',
 'imposdibilitando',
 'improvisadas',
 'imunológicas',
 'inacabada',
 'inapropriado',
 'incentivado',
 'incompetentes',
 'inconcebível',
 'incorretas',
 'incorreto',
 'indenizatória',
 'indevido',
 'index',
 'indicar',
 'indiferença',
 'indisposição',
 'individual',
 'infecção',
 'infiltra',
 'informacao',
 'informava',
 'informo',
 'informou',
 'inicia',
 'injusto',
 'inseguro',
 'inss',
 'instante',
 'insuficiência cardíaca',
 'inteiro',
 'intensificação',
 'interesses',
 'interlocutório',
 'internar',
 'intestino',
 'intuito',
 'invasão',
 'investe',
 'ipmc',
 'iptu',
 'ipva',
 'irmãos',
 'irregular',
 'isolamos',
 'iss',
 'isto',
 'isto for',
 'itararé',
 'jardim',
 'jd',
 'joanzinho',
 'joelho',
 'jus',
 'justificam',
 'kloss',
 'la',
 'ladrões',
 'lajotas',
 'las',
 'lastimável',
 'latem',
 'latido',
 'lavam',
 'lazer',
 'lc',
 'ldo',
 'lectospirose',
 'leem',
 'legitimidade',
 'lei',
 'lei destinam',
 'lei lei',
 'lei municipal',
 'lei seca',
 'leia',
 'leito',
 'leitos',
 'lembra',
 'lembrar',
 'letras',
 'leu',
 'levantei',
 'levarem',
 'levará',
 'levá',
 'lg',
 'lhes',
 'liberada',
 'ligeirinho',
 'limitada',
 'limpeza',
 'limpeza deverá',
 'limpeza pública',
 'limpeza terreno',
 'lindeiras',
 'linha',
 'linha amrarela',
 'linha vermelha',
 'linhas',
 'livre',
 'lixa',
 'lixeiras',
 'lixo',
 'lixo orgânico',
 'lixo reciclavel',
 'lixo vegetal',
 'lixão',
 'llixo',
 'lluminação',
 'lo',
 'lo oportunamente',
 'localiza',
 'localizacao',
 'login',
 'logradouros',
 'logradouros públicos',
 'longa',
 'los',
 'lotação',
 'lucia locher',
 'luminarias',
 'luminação pública',
 'luminária',
 'luminária bma',
 'luminária d3tbad',
 'luminária defeituosa',
 'luminária pública',
 'luminária trocada',
 'luminárias',
 'luminárias queimadas',
 'lumiária',
 'luta',
 'luxo',
 'luzes',
 'lâmpada',
 'lâmpada iluminação',
 'lâmpada pública',
 'lâmpada queimada',
 'lâmpadas',
 'lâmpadas queimadas',
 'lâmpadas queimam',
 'lâmpdas',
 'lãmpada',
 'machucado',
 'macrodrenagem',
 'macrodrenagem extravasamento',
 'madeiras leves',
 'mae',
 'magistério',
 'mais',
 'mal',
 'mal atendimento',
 'mal edcuados pararemmbem',
 'mal educadas',
 'mandam',
 'mania',
 'manisfestar',
 'manutenção',
 'manutenção asfalto',
 'marasmo',
 'marcava',
 'matagal',
 'mato',
 'mauro ignacio',
 'mauá',
 'maximo',
 'medicamento',
 'mei',
 'mei deverá optar',
 'meio',
 'meio ambiente',
 'meio público',
 'melhoramento',
 'menino',
 'menores',
 'mensagens',
 'mentiroso',
 'menu',
 'mercedes stresser',
 'mexendo',
 'mias',
 'micro',
 'midiane',
 'miguel',
 'minhaa',
 'mini rotatorio',
 'ministro',
 'minímo existencial',
 'mocós',
 'monento',
 'montamos',
 'moradia',
 'moradia popular',
 'moradores',
 'moradores daquele',
 'mortal',
 'mortes',
 'morto',
 'mortos',
 'mosquito',
 'mosquito aedes aegypt',
 'mosquito aedes egipicy',
 'mosquitos',
 'mosquitos aedes',
 'mostrarão',
 'moto',
 'motorista',
 'motorista disse',
 'motorista regularizados sentimos',
 'motorista tenha',
 'muitoo',
 'mulher',
 'multa',
 'multado',
 'multando',
 'multiloja',
 'municial',
 'municipais',
 'municipal',
 'médicas',
 'médicos',
 'najsmma',
 'nao',
 'nessas',
 'nestas linhas',
 'neto',
 'neuraldo achando',
 'nfs',
 'ninguém',
 'ninguém atendeu',
 'ninho',
 'ninho grande',
 'no',
 'no_msg&recuruit_context=fb_share_mention_control&fb_ref=default',
 'no_src',
 'noites',
 'norma',
 'nossas',
 'nosso',
 'nosso jardim',
 'nov',
 'nucleo',
 'numa',
 'numa coisa',
 'numa rua',
 'numa árvore',
 'nós',
 'nós deficientes',
 'nós moradores',
 'o',
 'oa',
 'obitos',
 'obras',
 'obras demora',
 'obrigatório',
 'observamos',
 'observando',
 'obstante',
 'obstrução',
 'ocorram',
 'oficiais',
 'omissa',
 'ondas',
 'onibus',
 'operar',
 'operação',
 'operação tapa',
 'operação tapa buraco',
 'operação tapa buracos',
 'operação “tapa',
 'orientado',
 'origem',
 'orione',
 'osso',
 'outras',
 'outras coisas',
 'outrem',
 'outrossim',
 'ouvidora',
 'ouvidoria',
 'ouvidoria municipal',
 'ouvidoria sanepar',
 'ouvidoria tenha',
 'oxigênio',
 'pagamento',
 'pagamento deverá',
 'pagável',
 'palavaras',
 'palhas',
 'panacas apressados',
 'par',
 'parabenizar',
 'paranasais',
 'pararam',
 'parcipa',
 'parece',
 'parental',
 'parquinho',
 'participações',
 'participações eireli',
 'pasme',
 'passaram',
 'passarão',
 'pau',
 'pavimentação',
 'pavimentação asfáltica',
 'pcontroller',
 'peca',
 'pedir',
 'pedrestes',
 'pega',
 'penalizada',
 'pensem',
 'pensão',
 'pequenas',
 'pequeno',
 'pequenos',
 'percebe',
 'perderam',
 'pergunto',
 'periogoso',
 'permito',
 'pernambuco',
 'pernilongos',
 'pernumbra',
 'perseguidos',
 'pertubação',
 'pertubações mentais',
 'pessoinhas',
 'peça',
 'pgm',
 'pintada',
 'pipocar',
 'placas',
 'plantio',
 'playgrond',
 'pluviais entupidas',
 'pluvial',
 'pluvial entupida',
 'poda',
 'podendo',
 'poder',
 'poder municipal',
 'poder público',
 'poder público municipal',
 'poder retirá',
 'podia',
 'podiamos',
 'poliesportivo pinheirão',
 'poluicao',
 'poluindo',
 'pompilia',
 'pompília',
 'popular',
 'popular linguiça',
 'portaria',
 'posso',
 'postagem difamatoria',
 'pouca',
 'pouca coisa',
 'poço',
 'praticantes',
 'precisar convocar',
 'prefeitura',
 'prefeitura contratou',
 'prefeitura decide',
 'prefeitura limita',
 'prefeitura municipal',
 'presenciado',
 'preservação',
 'prestam',
 'previa',
 'primeiros',
 'privando',
 'procon',
 'produzem',
 'proferiu',
 'profundidade',
 'pronuncie',
 'protolos',
 'prá',
 'própria',
 'própria ouvidoria',
 'própria prefeitura',
 'próprias',
 'próprios',
 'pt',
 'publicação',
 'publicidade',
 'publicidade irregular',
 'pública',
 'público',
 'público municipal',
 'públicos',
 'quais',
 'quantos',
 'que',
 'queima',
 'queima lixo doméstico',
 'queimada',
 'queimadas',
 'quis',
 'ralos',
 'raquel',
 'raízes',
 'reabertura',
 'reabram agendamento',
 'realizando',
 'realizasse',
 'recadastrado',
 'recarga',
 'recargas',
 'recente',
 'recolhem',
 'recolhimento',
 'recolhimento lixo',
 'reconheci',
 'recruiter=',
 'recuperação',
 'recusar',
 'recusaram',
 'reduturas',
 'reduz',
 'reduzindo',
 'reembolso',
 'refere',
 'referidos agentes',
 'refiro',
 'refletiu',
 'regra',
 'regulamentação',
 'regularizada',
 'regularizado',
 'reintegração',
 'relatório',
 'relatório circunstanciado',
 'religamento',
 'relocação',
 'remeto',
 'renomada',
 'renovado',
 'renovam',
 'repasse',
 'repintado',
 'reportei',
 'rescisão',
 'residuos',
 'residuos orgânicos',
 'residuos vegetais',
 'respaldo setran',
 'respeita',
 'respeitamos nosso deveremos',
 'respeitasse',
 'responsabilizou',
 'resposáveis',
 'ressalva',
 'ressarcimento',
 'restabelecimento',
 'resto',
 'resíduos',
 'resíduos rua',
 'resíduos vegetais',
 'retentando',
 'retirada',
 'retirada destas',
 'retirada destas caliças',
 'retiradas',
 'retirados cartazes',
 'retirá',
 'reto',
 'revalidar',
 'revalidação',
 'revitalizada',
 'revitalizado',
 'revoltante',
 'rezando',
 'reúnem',
 'ridícula',
 'rio',
 'rio \r\ngrande',
 'rio grande',
 'rodovias',
 'rompimento',
 'rotineira',
 'roubar',
 'roubo',
 'roçada',
 'rua',
 'rua carmelina cavassin',
 'rua guglielmo marconi',
 'rua jacarezinho',
 'rua lourival wendler',
 'rua mal',
 'rua marcopolo',
 'rua mercedes stresser',
 'rua nestas',
 'rua queimada',
 'rua rio grande',
 'rua sâo',
 's',
 's dirigi',
 'sabe',
 'sabê',
 'salario',
 'saliento',
 'sancionou',
 'sandino',
 'saneamento',
 'sanepar',
 'saporski',
 'saturação',
 'saímos',
 'saúde',
 'saúde pública',
 'scotti',
 'sedescrito',
 'segue',
 'segurança',
 'seguro',
 'semaforo',
 'semáforo',
 'semáforos',
 'semáforos rua',
 'sente',
 'sentei',
 'servir',
 'setram',
 'setran',
 'seção',
 'sgm',
 'sgn9i209',
 'si',
 'sic',
 'sigiloso',
 'silêncio',
 'sima',
 'sinaleiro',
 'sinaleiros',
 'sincronização',
 'sinduscon',
 'sine',
 'sinto',
 'siqueira',
 'sirvo',
 'sitaram',
 'sma',
 'smelj',
 'sobrenome',
 'solicita',
 'solicitam',
 'solicito',
 'solicitou',
 'solo',
 'solucionem',
 'somando',
 'sonoro',
 'soss',
 'sres',
 'stival',
 'su',
 'subistituiçaõ',
 'subitituidas',
 'submetidos',
 'substituiu',
 'substituição',
 'sujeira',
 'superdemora',
 'surpreende',
 'surpreendi',
 'sussego',
 'sustentar',
 'tacha',
 'talvez',
 'talvez tenha dengue',
 'tampouco',
 'tapa',
 'tapa buraco',
 'tapa buracos',
 'tapa burado',
 'tarja',
 'taxa',
 'taxista',
 'taxistas',
 'tco',
 'tecnologia',
 'tendo',
 'tenha',
 'tenha caixa',
 'tenho',
 'teriamos',
 'termin',
 'terminar',
 'terreno',
 'terreno baldio',
 'terreno enquanto',
 'terreno público',
 'terrivel',
 'testada',
 'ti',
 'tido',
 'toco',
 'tocos',
 'todavia',
 'todeschini',
 'todso',
 'tornando',
 'tornar',
 'toxoplasmose',
 'trabalhamos',
 'trafego',
 'trans issak',
 'transcrevê',
 'transfere',
 'transgredindo norma',
 'transido',
 'transito',
 'transito feitas',
 'transito inoperante',
 'transito pedidas',
 'transparencia',
 'transparência',
 'transparência ouvidoria',
 'transporta',
 'transportam clandestinamente',
 'trastornado',
 'tratar',
 'trazido',
 'tração',
 'treinada',
 'tributo',
 'tripla',
 'troca',
 'troca lâmpada',
 'troca lâmpada queimada',
 'trocada',
 'trocaram',
 'tronco',
 'troncos',
 'trouxa',
 'trânsito',
 'tubulação',
 'tumulto',
 'tutetar',
 'tê',
 'típica',
 'ubs',
 'uce30',
 'ucrânia',
 'uma',
 'unidade',
 'unidade básica',
 'unidade coloca',
 'upa',
 'urbanismo',
 'urbs',
 'usa',
 'utencilios',
 'vacina',
 'vacinação',
 'vacinação moradores',
 'vagas',
 'vagos',
 'valida',
 'vazamento',
 'vegetais',
 'vegetal',
 'veiculo',
 'veiculos',
 'vejo',
 'velha',
 'velociade',
 'vencimento',
 'vendendo',
 'vendendo doces',
 'vendo',
 'verde',
 'vereadores',
 'vereadores manfron',
 'veículo',
 'veículos',
 'veículos\r\nmeio',
 'veículos abandonados',
 'veículos alcoolizados',
 'viam',
 'viaria',
 'vindo',
 'vir',
 'virus gripais',
 'vizinha',
 'voltarão',
 'volto',
 'vê',
 'vês',
 'vó',
 'vôlei',
 'w',
 'wap',
 'watch',
 'zanicotti',
 'zerada',
 'zika virus',
 'zona',
 'zoneamento',
 'zoológico',
 '{',
 '}',
 '\x7f\x7f\x7f',
 '§',
 '°',
 '° circunscrição',
 '´',
 '´amais',
 'àquele',
 'àrvore',
 'águas',
 'águas pluvais',
 'águas pluviais',
 'álvara',
 'álvaras',
 'área',
 'área pública',
 'árvore',
 'árvore mal',
 'árvores',
 'ônibos',
 'ônibus',
 'ônibus interestaduais',
 'õnibus',
 'últimas',
 'últimos',
 '“',
 '“capciosa',
 '“esperto',
 '“gênios',
 '“lagos',
 '“ligados',
 '“sonorizador',
 '“sonorizadores',
 '“área',
 '”',
 '\u202a#\u200e',
 '\u202a#\u200esanepar']

with open('arquivo.txt', 'w') as arq:
    arq.writelines('\n'.join(l))
